"""批量入库 25 个澳洲特有/公职类职业（2026-06）+ 生成 markdown。
- A 组（福利/澳洲特有，10 个）：NDIS 支持协调员、行为支持师、NDIS 计划管理、本地协调员(LAC)、
  居家照护配套协调员、持牌理财顾问、业主立案法团经理、买方代理、原住民健康工作者、石棉清除工。
- B 组（公职人员，15 个，is_public_servant=1，分类 Government & Public Sector）。
薪资为联网检索（Seek/Glassdoor/Indeed/PayScale/APS EA 2025-2026）区间估算，仍需二次核对。
均非技术移民职业（is_migration=0）。可重复运行（seed_occupation_v2 幂等）。
运行：python -m scripts.seed_batch_public_au   （需先跑 migrate_public_servant）
"""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.dirname(__file__))
from db.connection import get_cursor
from _seed_helper import seed_occupation_v2
from pipeline.generators.md_generator import generate_md


def R(d):
    return [{"dimension": k, "label_zh": v[0], "stars": v[1]} for k, v in d.items()]


def EDU(rows):
    return [{"stage": s, "duration": dur, "cost_min": a, "cost_max": b, "cost_note": n, "sort_order": i}
            for i, (s, dur, a, b, n) in enumerate(rows)]


def QUAL(rows):
    return [{"qual_name": q, "issuer": iss, "note": nt, "is_mandatory": m, "sort_order": i}
            for i, (q, iss, nt, m) in enumerate(rows)]


def LIST(rows):
    return [{"platform": p, "count_min": a, "count_max": b, "note": n} for (p, a, b, n) in rows]


def SAL(rows):
    return [{"experience": e, "salary_min": a, "salary_max": b, "salary_note": n, "sort_order": i}
            for i, (e, a, b, n) in enumerate(rows)]


def FAQ(rows):
    return [{"faq_type": t, "sort_order": i, "question": q, "answer": a} for i, (t, q, a) in enumerate(rows)]


SRC_JSA = ("JSA / JobOutlook", "ANZSCO 就业、人数与需求", "https://www.jobsandskills.gov.au/")
SRC_SEEK = ("Seek AU", "薪资与岗位量参考", "https://www.seek.com.au/")

# 非移民职业通用：PR 友好度低 / PR 难度高
PR_NONMIG = {"pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)}

GOV = "Government & Public Sector"
HEALTH = "Healthcare & Care"
BFL = "Business, Finance & Legal"
TRADE = "Trades & Construction"

# ───────────────────────── 25 个职业数据 ─────────────────────────
OCCS = [
 # ========== A 组：福利 / 澳洲特有（非公职） ==========
 dict(code="411716", en="NDIS Support Coordinator", zh="NDIS 支持协调员", cat=HEALTH, pub=0,
      wf=30000, growth=["NDIS Scheme Growth", "Specialist Support Coordination", "Participant Outcomes", "Plan Implementation"],
      sum_zh="NDIS 支持协调员帮助残障计划参与者理解并落地其 NDIS 计划：对接服务商、协调支持、处理危机，是澳洲国家残障保险计划(NDIS)体系内的核心角色，需求随计划扩张持续增长，非技术移民职业。",
      sum_en="NDIS Support Coordinators help participants understand and implement their NDIS plans, connecting them with providers and coordinating supports; a core role inside Australia's National Disability Insurance Scheme, not a skilled migration occupation.",
      fc="NDIS 持续扩张带动支持协调员需求稳定增长，具备专科支持协调(Specialist)能力与残障/社工背景者更抢手。",
      tr="路径：支持协调员→专科支持协调→团队负责人；熟悉 NDIS 价格指南与计划落地流程者更具竞争力。",
      edu=[("Certificate IV / Diploma in Community Services / Disability（常见）", "1~2年", 3000, 18000, "或相关社工/护理背景"),
           ("NDIS Worker Screening Check", "数周", 100, 150, "强制工牌核查")],
      qual=[("NDIS Worker Screening Check", "各州/领地核查机构", "强制", 1),
            ("Diploma of Community Services / 相关学历", "TAFE/RTO/大学", "入行基础", 0)],
      listings=[("Seek", 1500, 3000, "全国"), ("Indeed", 1000, 2200, "全国"), ("Jora", 800, 1800, "全国")],
      sal=[("初级（0-3年）", 65000, 78000, "Entry"), ("中级（3-8年）", 78000, 92000, "Experienced"), ("资深 / 专科协调", 92000, 110000, "Specialist")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["有社工/残障/护理背景想转协调岗者", "擅长沟通、协调与个案管理的人", "认同助残价值、抗压能力强者"],
      unfit=["以技术移民为目标者", "不擅长处理危机与复杂个案者"],
      faqs=[("salary", "NDIS 支持协调员澳洲薪资多少？", "约 AUD $6.5万~$11万，专科支持协调更高，多按 SCHADS Award 定级。"),
            ("migration", "NDIS 支持协调员能技术移民吗？", "一般不能，不在技术移民清单上，属于本地就业型职业。")]),

 dict(code="272615", en="Behaviour Support Practitioner", zh="行为支持师", cat=HEALTH, pub=0,
      wf=12000, growth=["NDIS Positive Behaviour Support", "Restrictive Practice Reduction", "Practitioner Capability", "Allied Health Crossover"],
      sum_zh="行为支持师为有复杂行为需求的残障人士设计并执行积极行为支持(PBS)计划，受 NDIS Quality and Safeguards Commission 监管并须通过能力评估，薪资较高、需求旺盛，非技术移民职业。",
      sum_en="Behaviour Support Practitioners design and deliver positive behaviour support plans for people with complex needs; regulated by the NDIS Quality and Safeguards Commission, well-paid and in demand, not a skilled migration occupation.",
      fc="NDIS 减少限制性做法的政策推动行为支持师需求快速增长，心理/社工/作业治疗背景者尤其抢手。",
      tr="路径：初级→熟练→高级/顾问；通过 NDIS Commission 能力等级评估、积累复杂个案经验者收入显著提升。",
      edu=[("心理学/社工/作业治疗/教育等相关本科（常见）", "3~4年", 20000, 45000, "多数雇主要求"),
           ("NDIS PBS Capability 自评与证据", "持续", 0, 2000, "Commission 能力框架")],
      qual=[("NDIS Worker Screening Check", "各州核查机构", "强制", 1),
            ("相关本科/研究生学历", "认可大学", "入行基础", 0),
            ("PBS Capability 等级（Core→Advanced）", "NDIS Commission", "能力评定", 0)],
      listings=[("Seek", 1200, 2500, "全国"), ("Indeed", 800, 1800, "全国"), ("Jora", 600, 1400, "全国")],
      sal=[("初级（0-2年）", 70000, 85000, "Entry"), ("中级（2-6年）", 90000, 110000, "Experienced"), ("高级 / 顾问", 110000, 140000, "Senior / 独立顾问更高")],
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中高", 4),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["心理/社工/作业治疗等背景者", "擅长行为分析与计划设计的人", "想进入高薪助残专业岗者"],
      unfit=["不愿读相关学位者", "排斥处理复杂行为与风险个案者"],
      faqs=[("salary", "行为支持师澳洲薪资多少？", "约 AUD $7万~$14万，独立顾问时薪可达 $100~$160。"),
            ("migration", "行为支持师能技术移民吗？", "通常不能单独走技术移民；若持心理学家/作业治疗师等注册资格，则按对应注册职业评估。")]),

 dict(code="551113", en="NDIS Plan Manager", zh="NDIS 计划管理员", cat=HEALTH, pub=0,
      wf=15000, growth=["Plan Management Services", "NDIS Claiming & Compliance", "Bookkeeping Automation", "Participant Finance"],
      sum_zh="NDIS 计划管理员代参与者管理 NDIS 资金：审核发票、向 NDIA 报销、跟踪预算并出具报表，是 NDIS 三种资金管理方式之一，偏财务行政，门槛较低、入职快，非技术移民职业。",
      sum_en="NDIS Plan Managers manage participants' NDIS funding — processing invoices, claiming from the NDIA, tracking budgets and reporting; a finance-administration role within the scheme, not a skilled migration occupation.",
      fc="选择计划管理的参与者比例上升，带动稳定需求；熟悉 NDIS 报销系统与记账软件者更稳。",
      tr="路径：计划管理员→高级/团队主管；具备记账(BAS/Xero)与 NDIS 合规经验者更抢手。",
      edu=[("Certificate / 记账或商科背景（可选）", "0~1年", 0, 8000, "在岗培训为主"),
           ("NDIS 系统与报销流程培训", "数周", 0, 1500, "雇主提供")],
      qual=[("记账 / 商科证书（可选）", "TAFE/RTO", "非强制", 0),
            ("NDIS Worker Screening Check", "各州核查机构", "部分岗位要求", 0)],
      listings=[("Seek", 800, 1800, "全国"), ("Indeed", 600, 1400, "全国")],
      sal=[("初级（0-2年）", 55000, 65000, "Entry"), ("中级（2-5年）", 65000, 80000, "Experienced"), ("资深 / 主管", 80000, 95000, "Senior")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("很短", 1), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("良好", 4), "ai_risk": ("中高", 4), **PR_NONMIG},
      fit=["细心、擅长财务与流程的人", "记账/行政背景想进入 NDIS 领域者"],
      unfit=["以技术移民为目标者", "不喜欢重复性对账与报销工作者"],
      faqs=[("salary", "NDIS 计划管理员澳洲薪资多少？", "约 AUD $5.5万~$9.5万，资深或主管更高。"),
            ("migration", "NDIS 计划管理员能技术移民吗？", "不能，属于本地行政财务型职业，不在技术移民清单上。")]),

 dict(code="411715", en="Local Area Coordinator (NDIS)", zh="NDIS 本地协调员(LAC)", cat=HEALTH, pub=0,
      wf=10000, growth=["NDIS Partners in the Community", "Community Connection", "Plan Access & Reviews", "Mainstream Linkages"],
      sum_zh="本地协调员(LAC)受 NDIS Partners in the Community 项目委托(由政府外包给 APM、Mission Australia 等机构)，帮助参与者申请、理解并使用 NDIS 计划，并连接社区与主流服务，非技术移民职业。",
      sum_en="Local Area Coordinators, engaged through the NDIS Partners in the Community program, help participants access and use their NDIS plans and link to community and mainstream services; not a skilled migration occupation.",
      fc="作为 NDIS 与参与者之间的桥梁，LAC 需求随计划覆盖扩大保持稳定，社工/社区服务背景者更具优势。",
      tr="路径：LAC→高级 LAC/团队负责人；积累个案与社区资源者更易晋升。",
      edu=[("Certificate IV / Diploma in Community Services（常见）", "1~2年", 3000, 16000, "或社工背景"),
           ("NDIS Worker Screening Check", "数周", 100, 150, "强制")],
      qual=[("NDIS Worker Screening Check", "各州核查机构", "强制", 1),
            ("社区服务 / 社工相关学历", "TAFE/大学", "入行基础", 0)],
      listings=[("Seek", 700, 1600, "全国"), ("Indeed", 500, 1200, "全国")],
      sal=[("初级（0-3年）", 75000, 85000, "含 super 包"), ("中级（3-8年）", 85000, 100000, "Experienced"), ("资深 / 团队负责", 100000, 119000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["社区服务/社工背景者", "擅长沟通与资源连接的人", "认同助残价值者"],
      unfit=["以技术移民为目标者", "不擅长面对面服务与外勤者"],
      faqs=[("salary", "NDIS 本地协调员薪资多少？", "约 AUD $7.5万~$11.9万(常含 super 包)。"),
            ("migration", "本地协调员能技术移民吗？", "不能，属于本地就业型职业，不在技术移民清单上。")]),

 dict(code="134215", en="Home Care Package Coordinator", zh="居家照护配套协调员", cat=HEALTH, pub=0,
      wf=20000, growth=["Support at Home Reform", "Home Care Packages", "Aged Care Case Management", "Consumer Directed Care"],
      sum_zh="居家照护配套协调员/个案经理为长者管理政府补贴的居家照护配套(HCP，2025 年起并入 Support at Home)：评估需求、安排服务、管理预算并对接家庭，是澳洲安老体系内的稳定中高薪岗位，非技术移民职业。",
      sum_en="Home Care Package Coordinators / case managers manage government-subsidised home care for older Australians — assessing needs, arranging services and managing budgets within Australia's aged-care system; not a skilled migration occupation.",
      fc="人口老龄化与 Support at Home 改革推动居家照护管理需求持续增长，具备个案管理与预算经验者更抢手。",
      tr="路径：协调员→高级个案经理→服务经理；熟悉 HCP/Support at Home 拨款规则者收入更高。",
      edu=[("护理/老年学/社区服务相关学历（常见）", "1~3年", 3000, 30000, "或相关经验"),
           ("Police Check / NDIS or Aged Care 工牌核查", "数周", 100, 200, "强制")],
      qual=[("相关学历或安老照护经验", "TAFE/大学", "入行基础", 0),
            ("National Police Check", "AFP/各州", "强制", 1)],
      listings=[("Seek", 1500, 3000, "全国"), ("Indeed", 1000, 2200, "全国")],
      sal=[("初级（0-3年）", 75000, 85000, "Entry"), ("中级（3-8年）", 85000, 100000, "Experienced"), ("资深 / 服务经理", 100000, 120000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["护理/安老背景想转管理岗者", "擅长个案管理与协调的人", "有同理心、抗压者"],
      unfit=["以技术移民为目标者", "不适应长者与家庭情绪压力者"],
      faqs=[("salary", "居家照护协调员澳洲薪资多少？", "约 AUD $7.5万~$12万，资深个案经理/服务经理更高。"),
            ("migration", "这个职业能技术移民吗？", "若持注册护士资格可走护理移民；纯协调/个案管理岗一般不在技术移民清单上。")]),

 dict(code="222313", en="Financial Adviser", zh="持牌理财顾问", cat=BFL, pub=0,
      wf=16000, growth=["Advice Fee Models", "Retirement & Super Advice", "FASEA Professional Standards", "Holistic Financial Planning"],
      sum_zh="持牌理财顾问为客户提供个人理财、退休金(Super)、保险与投资建议，须在 AFSL 下执业、满足 ASIC 的专业学历与考试标准(原 FASEA 框架)，行业供给紧缩使经验顾问薪资走高，非技术移民职业。",
      sum_en="Financial Advisers provide personal advice on superannuation, insurance and investments; they must operate under an AFSL and meet ASIC's education and exam standards. Tight supply has pushed experienced advisers' pay up; not a skilled migration occupation.",
      fc="持牌顾问人数因合规门槛下降而供不应求，经验顾问薪资 2025 年显著上涨，专业化与退休金建议需求强。",
      tr="路径：副顾问/Paraplanner→持牌顾问→高级/合伙人；积累客户簿与专业认证者收入可观。",
      edu=[("金融/商科相关本科 + 认可学历", "3~4年", 20000, 45000, "ASIC 学历标准"),
           ("Financial Adviser Exam + Professional Year", "1年", 1000, 5000, "执业前提")],
      qual=[("AFSL 授权 / Adviser Register 登记", "ASIC", "强制执业", 1),
            ("认可金融学历 + Financial Adviser Exam", "认可机构/ASIC", "强制", 1),
            ("Professional Year (PY)", "持牌机构", "新人强制", 1)],
      listings=[("Seek", 1500, 3000, "全国"), ("LinkedIn", 1200, 2500, "全国")],
      sal=[("初级 / 副顾问（0-3年）", 75000, 95000, "含 PY"), ("中级（3-8年）", 100000, 140000, "Experienced"), ("资深 / 合伙人", 150000, 200000, "含奖金，部分更高")],
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("高", 4),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["对理财/投资有兴趣并能持续学习者", "擅长沟通、建立长期客户关系的人", "愿意完成学历与执业考试者"],
      unfit=["排斥合规与持续教育者", "以技术移民为目标者"],
      faqs=[("salary", "持牌理财顾问澳洲薪资多少？", "约 AUD $7.5万~$20万+，经验顾问近年涨幅明显，州际差异大。"),
            ("migration", "理财顾问能技术移民吗？", "本职位(个人理财建议)一般不在技术移民清单；Financial Investment Adviser(222311)另有评估路径。")]),

 dict(code="612115", en="Strata Manager", zh="业主立案法团经理", cat=BFL, pub=0,
      wf=15000, growth=["Strata Title Growth", "Apartment Living", "Building Compliance", "Owners Corporation Management"],
      sum_zh="业主立案法团经理(Strata/Body Corporate Manager)管理公寓与综合楼盘的业主立案法团：召开会议、收取与管理公共基金、安排维修与保险、处理合规，是澳洲(及新西兰)特有的 strata title 制度下的岗位，各州持牌，需求随公寓化上升，非技术移民职业。",
      sum_en="Strata (body corporate) managers run owners corporations for apartment and mixed-use buildings — meetings, levies, maintenance, insurance and compliance; a role unique to Australia's strata-title system, licensed by state, not a skilled migration occupation.",
      fc="城市公寓化与楼盘合规要求推动稳定需求，持牌且擅长财务与冲突处理者更抢手。",
      tr="路径：助理→Strata Manager→高级/Portfolio Manager；管理楼盘组合规模与合规经验决定收入。",
      edu=[("各州 Strata Managing Agent 牌照培训", "数月", 1500, 6000, "强制持牌"),
           ("Certificate IV / 物业相关（常见）", "0~1年", 2000, 8000, "加分")],
      qual=[("Strata Managing Agent Licence / 各州注册", "各州 Fair Trading / 监管机构", "强制持牌", 1),
            ("Certificate IV in Strata Community Management（部分州）", "RTO", "持牌要求", 0)],
      listings=[("Seek", 1500, 3000, "全国"), ("Indeed", 1000, 2000, "全国")],
      sal=[("初级 / 助理（0-3年）", 70000, 85000, "Entry"), ("中级（3-8年）", 85000, 110000, "Experienced"), ("资深 / Portfolio", 110000, 150000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["擅长财务、组织与冲突处理的人", "想进入物业/房地产相关稳定岗者"],
      unfit=["不愿处理业主纠纷与会议者", "以技术移民为目标者"],
      faqs=[("salary", "业主立案法团经理澳洲薪资多少？", "约 AUD $7万~$15万，悉尼及大楼盘组合更高。"),
            ("migration", "Strata Manager 能技术移民吗？", "不能，属于本地持牌职业，不在技术移民清单上。")]),

 dict(code="612114", en="Buyer's Agent", zh="买方代理", cat=BFL, pub=0,
      wf=8000, growth=["Buyers Advocacy", "Property Investment", "Off-market Deals", "Data-driven Sourcing"],
      sum_zh="买方代理(Buyer's Agent/Advocate)代表购房者寻找、评估并议价购入房产，受各州 fair trading 监管并需房地产从业牌照，近年随房产投资热兴起，收入与成交挂钩、上限高，非技术移民职业。",
      sum_en="Buyer's agents represent purchasers to search, evaluate and negotiate property on their behalf; licensed under state fair-trading rules and increasingly popular with property investors. Income is commission-linked with a high ceiling; not a skilled migration occupation.",
      fc="房产投资与议价服务需求上升带动增长，自带客源、擅长议价与数据选房者收入可观但波动大。",
      tr="路径：助理→买方代理→自营/合伙；客户口碑、成交量与佣金结构决定收入上限。",
      edu=[("各州房地产从业证书 / 牌照", "数周~数月", 1000, 5000, "强制持牌"),
           ("房产投资 / 估价相关培训（可选）", "持续", 0, 8000, "加分")],
      qual=[("Real Estate Agent / Buyer's Agent Licence", "各州 Fair Trading", "强制持牌", 1),
            ("房地产从业证书", "RTO", "入行基础", 0)],
      listings=[("Seek", 400, 900, "全国"), ("LinkedIn", 500, 1100, "全国")],
      sal=[("初级（0-2年）", 75000, 100000, "底薪+少量佣金"), ("中级（2-6年）", 120000, 160000, "佣金为主"), ("资深 / 自营", 200000, 300000, "含佣金，波动大")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("较短", 2), "certification_difficulty": ("中等", 3),
           "job_demand": ("中等", 3), "competition": ("中高", 4), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["擅长议价、销售与客户关系的人", "对房产市场敏感、能承受收入波动者"],
      unfit=["排斥业绩/佣金压力者", "以技术移民为目标者"],
      faqs=[("salary", "买方代理澳洲收入多少？", "约 AUD $7.5万~$30万，多与成交佣金挂钩，资深自营上限很高但波动大。"),
            ("migration", "买方代理能技术移民吗？", "不能，属于本地持牌销售型职业，不在技术移民清单上。")]),

 dict(code="411511", en="Aboriginal & Torres Strait Islander Health Worker", zh="原住民健康工作者", cat=HEALTH, pub=0,
      wf=12000, growth=["Closing the Gap", "ACCHO Sector", "Cultural Safety", "Primary Health Care"],
      sum_zh="原住民健康工作者在原住民社区控制的健康服务(ACCHO)及公立医疗系统中提供文化安全的初级医疗、健康教育与个案支持，受 Aboriginal and Torres Strait Islander Health Award 覆盖，是政府资助、澳洲特有的岗位，偏远地区薪资更高，非技术移民职业。",
      sum_en="Aboriginal and Torres Strait Islander Health Workers deliver culturally safe primary care, health education and case support in community-controlled (ACCHO) and public health services; a government-funded, uniquely Australian role, not a skilled migration occupation.",
      fc="Closing the Gap 政策与 ACCHO 扩张推动稳定需求，持注册资格(Health Practitioner)及偏远地区从业者收入更高。",
      tr="路径：健康工作者→注册健康从业者(Practitioner)→团队/项目负责人；文化身份与社区联系是核心优势。",
      edu=[("Certificate III/IV in Aboriginal and/or Torres Strait Islander PHC", "1~2年", 0, 8000, "多有补贴"),
           ("注册(Health Practitioner)所需 Cert IV", "1~2年", 0, 9000, "AHPRA 注册路径")],
      qual=[("Cert III/IV in ATSI Primary Health Care", "TAFE/RTO", "入行基础", 1),
            ("AHPRA 注册（Health Practitioner 岗位）", "AHPRA / 相关委员会", "注册岗位强制", 0)],
      listings=[("Seek", 600, 1300, "全国"), ("Health Workforce", 400, 900, "ACCHO/公立")],
      sal=[("初级（0-3年）", 60000, 72000, "Award 起薪"), ("中级（3-8年）", 75000, 95000, "Experienced"), ("资深 / 注册从业者", 95000, 120000, "偏远更高")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["原住民/托雷斯海峡岛民社区成员", "认同文化安全与社区健康者", "愿在偏远地区服务者"],
      unfit=["以技术移民为目标者", "无法建立社区信任与文化联系者"],
      faqs=[("salary", "原住民健康工作者薪资多少？", "约 AUD $6万~$12万，偏远地区与注册健康从业者更高。"),
            ("migration", "这个职业能技术移民吗？", "不能，是面向原住民社区、政府资助的本地岗位，不在技术移民清单上。")]),

 dict(code="899211", en="Asbestos Removalist", zh="石棉清除工", cat=TRADE, pub=0,
      wf=10000, growth=["Asbestos Remediation", "WHS Licensing", "Demolition & Renovation", "Hazardous Material Handling"],
      sum_zh="石棉清除工负责安全拆除与处置含石棉材料，受澳洲严格的 WHS(职业健康安全)制度监管，须持 A 类/B 类石棉清除牌照，需求稳定、加班与津贴使收入可观，非技术移民职业。",
      sum_en="Asbestos removalists safely remove and dispose of asbestos-containing materials under Australia's strict WHS regime; holding a Class A/B asbestos removal licence. Steady demand with overtime/allowances lifting pay; not a skilled migration occupation.",
      fc="老旧建筑改造与拆除带动稳定需求，持 A 类牌照(可处理任何石棉)与监督资格者收入更高。",
      tr="路径：清除工→班组长→监督(Supervisor)；牌照等级与 WHS 监督经验决定收入。",
      edu=[("石棉清除资格 (Cert) + 各州牌照", "数周~数月", 500, 4000, "强制持牌"),
           ("White Card (建筑工地)", "1天", 100, 200, "强制")],
      qual=[("Class A / B Asbestos Removal Licence", "各州 WHS 监管机构(如 SafeWork)", "强制持牌", 1),
            ("Construction Induction (White Card)", "RTO", "强制", 1)],
      listings=[("Seek", 500, 1200, "全国"), ("Indeed", 400, 1000, "全国")],
      sal=[("初级（0-3年）", 56000, 70000, "时薪约$30~$37"), ("中级（3-8年）", 70000, 90000, "含加班"), ("监督 / 资深", 90000, 120000, "Supervisor")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), **PR_NONMIG},
      fit=["不介意体力与防护装备作业者", "想快速持牌入行的技工", "注重安全规范的人"],
      unfit=["排斥高温/防护服与危险材料作业者", "以技术移民为目标者"],
      faqs=[("salary", "石棉清除工澳洲薪资多少？", "约 AUD $5.6万~$12万，监督岗更高，加班与津贴影响大。"),
            ("migration", "石棉清除工能技术移民吗？", "不能，属于本地持牌技工岗，不在技术移民清单上。")]),

 # ========== B 组：公职人员（is_public_servant=1，分类 Government & Public Sector）==========
 dict(code="531112", en="Public Servant / Government Administration Officer", zh="政府行政官员（公务员）", cat=GOV, pub=1,
      wf=200000, growth=["APS Workforce", "Policy Implementation", "Digital Government", "Service Delivery"],
      sum_zh="政府行政官员是澳洲公共服务体系(APS 联邦/各州公务员)的通用岗位，按 APS1–6 等级承担行政、协调、政策执行与服务交付，工作稳定、福利好(15.4% 退休金)，类似国内公务员，非技术移民职业。",
      sum_en="Government administration officers are general public-service roles (APS / state government) graded APS1–6, handling administration, coordination, policy implementation and service delivery; stable with strong benefits, not a skilled migration occupation.",
      fc="政府数字化与服务交付改革带动稳定招聘，具备数据、项目与政策执行能力者晋升更快。",
      tr="路径：APS3/4→APS5/6→EL1/EL2；公民身份(多数岗位要求)与安全审查是关键门槛。",
      edu=[("高中 / 相关本科（视等级）", "0~4年", 0, 45000, "高等级岗多需学位"),
           ("Australian Citizenship + Security Clearance", "数周~数月", 0, 0, "多数岗位强制")],
      qual=[("Australian Citizenship", "—", "多数岗位强制", 1),
            ("相关学历（按等级）", "认可机构", "高等级要求", 0)],
      listings=[("APSjobs", 3000, 6000, "联邦"), ("I work for NSW / 各州", 2500, 5000, "州政府"), ("Seek", 2000, 4000, "全国")],
      sal=[("APS3 / 初级", 60000, 72000, "Entry"), ("APS4 / 中级", 73000, 86000, "Experienced"), ("APS5–6 / 资深", 89000, 110000, "+15.4% super")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中高", 4), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["有澳洲公民身份、求稳定与福利者", "擅长行政、协调与流程的人", "认同公共服务价值者"],
      unfit=["非公民/无法通过安全审查者", "追求高薪或快速晋升者", "以技术移民为目标者"],
      faqs=[("salary", "澳洲政府行政官员薪资多少？", "APS3 约 $6万起，APS5–6 约 $9万~$11万，外加 15.4% 退休金，州政府类似。"),
            ("migration", "公务员岗位能技术移民吗？", "不能，且多数岗位要求澳洲公民身份，不在技术移民清单上。")]),

 dict(code="541112", en="Government Customer Service Officer", zh="政府客户服务官员", cat=GOV, pub=1,
      wf=60000, growth=["Services Australia", "Digital Channels", "Citizen Services", "Contact Centre Ops"],
      sum_zh="政府客户服务官员在 Services Australia(Centrelink/Medicare)、州政府服务中心等为公众办理福利、证件与咨询，按 APS2–4 定级，入职门槛较低、是进入公职体系的常见起点，非技术移民职业。",
      sum_en="Government customer service officers serve the public at Services Australia (Centrelink/Medicare) and state service centres, graded around APS2–4; an accessible entry point into the public sector, not a skilled migration occupation.",
      fc="政府服务量大且持续数字化，客服岗是进入公职的常见入口，表现好者可内部转岗晋升。",
      tr="路径：客服官员→团队主管/专员→其他公职岗；熟悉系统与合规流程者更易内部发展。",
      edu=[("高中 / Certificate（可选）", "0~1年", 0, 4000, "在岗培训为主"),
           ("Australian Citizenship", "—", 0, 0, "多数岗位强制")],
      qual=[("Australian Citizenship", "—", "多数岗位强制", 1),
            ("National Police Check", "AFP/各州", "强制", 1)],
      listings=[("APSjobs", 1500, 3500, "联邦"), ("Seek", 1500, 3000, "全国")],
      sal=[("APS2 / 入门", 58000, 65000, "Entry"), ("APS3 / 有经验", 65000, 75000, "Experienced"), ("APS4 / 资深", 75000, 85000, "+15.4% super")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("很短", 1), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), **PR_NONMIG},
      fit=["有公民身份、想进入公职的新人", "亲和、抗压、擅长沟通者"],
      unfit=["非公民者", "不适应高话务量与情绪劳动者", "以技术移民为目标者"],
      faqs=[("salary", "政府客服官员薪资多少？", "约 AUD $5.8万~$8.5万(APS2–4)，外加 15.4% 退休金。"),
            ("migration", "政府客服能技术移民吗？", "不能，且通常要求澳洲公民身份。")]),

 dict(code="599613", en="Local Council Officer", zh="地方议会职员", cat=GOV, pub=1,
      wf=190000, growth=["Local Government Services", "Community Programs", "Planning & Compliance", "Infrastructure Delivery"],
      sum_zh="地方议会职员在市/郡议会(Local Council)从事行政、规划、社区服务、合规与设施管理等，受 Local Government Award 或企业协议覆盖，是各地稳定的公共部门岗位，非技术移民职业。",
      sum_en="Local council officers work in city/shire councils across administration, planning, community services, compliance and facilities; covered by the Local Government Award or enterprise agreements, a stable public-sector role, not a skilled migration occupation.",
      fc="地方政府服务与基建项目支撑稳定需求，具备规划、合规或工程背景者岗位更多。",
      tr="路径：officer→coordinator→manager；专业方向(规划/环境/工程)决定收入与晋升。",
      edu=[("高中 / 相关本科或证书（视岗位）", "0~4年", 0, 40000, "专业岗需学位")],
      qual=[("相关专业资质（按岗位）", "认可机构", "专业岗要求", 0),
            ("National Police Check / Working with Children（部分岗）", "各州", "部分岗强制", 0)],
      listings=[("Seek", 2000, 4000, "全国"), ("council 官网", 1500, 3000, "各议会")],
      sal=[("初级（0-3年）", 62000, 75000, "Entry"), ("中级（3-8年）", 75000, 92000, "Experienced"), ("资深 / 协调", 92000, 110000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["想在本地稳定就业的公共部门求职者", "擅长行政、规划或社区服务者"],
      unfit=["追求高薪与快速晋升者", "以技术移民为目标者"],
      faqs=[("salary", "地方议会职员薪资多少？", "约 AUD $6.2万~$11万，专业岗(规划/工程)更高。"),
            ("migration", "议会职员能技术移民吗？", "不能，属于本地公共部门岗位，不在技术移民清单上。")]),

 dict(code="511113", en="Program / Project Officer (Government)", zh="政府项目官员", cat=GOV, pub=1,
      wf=90000, growth=["Program Delivery", "Stakeholder Engagement", "Grants & Funding", "Policy Projects"],
      sum_zh="政府项目/项目官员在联邦与州政府负责项目协调、干系人沟通、报告与资金管理，是政策落地与公共项目交付的执行岗，APS5–6 居多，需求稳定，非技术移民职业。",
      sum_en="Government program/project officers coordinate projects, engage stakeholders, report and manage funding across federal and state agencies — the delivery layer for policy and public programs, typically APS5–6; not a skilled migration occupation.",
      fc="政府项目化交付增多带动稳定需求，具备项目管理、数据与干系人沟通能力者更抢手。",
      tr="路径：项目官员→高级项目官员→项目经理/EL1；项目管理资质(如 PRINCE2)加分。",
      edu=[("相关本科（常见）", "3~4年", 20000, 45000, "多数岗位要求"),
           ("项目管理资质（可选）", "数月", 1000, 6000, "加分")],
      qual=[("相关学历", "认可大学", "入行基础", 0),
            ("Australian Citizenship（多数岗）", "—", "多数岗强制", 0)],
      listings=[("APSjobs", 2000, 4500, "联邦"), ("I work for NSW / 各州", 2000, 4000, "州政府"), ("Seek", 1800, 3500, "全国")],
      sal=[("初级（0-3年）", 75000, 86000, "Entry"), ("中级（3-8年）", 86000, 104000, "APS5–6"), ("资深 / 项目经理", 104000, 125000, "EL1")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中高", 4), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["擅长协调、写报告与项目管理的人", "有学位、想进入公职项目岗者"],
      unfit=["不擅长干系人沟通与文书者", "以技术移民为目标者"],
      faqs=[("salary", "政府项目官员薪资多少？", "约 AUD $7.5万~$12.5万(APS5–EL1)，外加 15.4% 退休金。"),
            ("migration", "政府项目官员能技术移民吗？", "不能，多要求公民身份，不在技术移民清单上。")]),

 dict(code="411713", en="Child Protection Officer / Caseworker", zh="儿童保护官员", cat=GOV, pub=1,
      wf=25000, growth=["Child Safety", "Out-of-home Care", "Family Support", "Statutory Casework"],
      sum_zh="儿童保护官员/个案工作者在州政府儿童安全部门负责风险评估、家庭介入与法定个案管理，工作意义大但压力高，州政府按专门 Award 定级、薪资较高，长期紧缺，非技术移民职业。",
      sum_en="Child protection officers / caseworkers carry out risk assessment, family intervention and statutory casework in state child-safety departments; meaningful but high-pressure work, well-paid under dedicated awards and chronically short-staffed; not a skilled migration occupation.",
      fc="人手长期紧缺使州政府持续大量招聘，社工/心理/相关学位者优先，留存率与抗压能力是关键。",
      tr="路径：个案工作者→高级/牵头个案工作者→主管；社工学历与法定个案经验决定发展。",
      edu=[("社工/心理/相关本科（多数州要求）", "3~4年", 20000, 45000, "法定岗位要求"),
           ("Working with Children Check + Police Check", "数周", 100, 300, "强制")],
      qual=[("相关本科学历(社工等)", "认可大学", "法定岗位要求", 1),
            ("Working with Children Check", "各州", "强制", 1)],
      listings=[("I work for NSW / 各州", 1500, 3000, "州政府"), ("Seek", 1200, 2500, "全国")],
      sal=[("初级 / 毕业生（0-2年）", 75000, 85000, "Graduate"), ("中级（2-6年）", 85000, 103000, "Caseworker"), ("资深 / 牵头", 103000, 120000, "Senior")],
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("高", 5), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), **PR_NONMIG},
      fit=["社工/心理背景、抗压能力强者", "有使命感、愿处理复杂家庭个案者"],
      unfit=["难以承受高情绪压力与风险者", "以技术移民为目标者"],
      faqs=[("salary", "儿童保护官员薪资多少？", "约 AUD $7.5万~$12万，NSW 等州 Caseworker 薪资偏高。"),
            ("migration", "儿童保护官员能技术移民吗？", "本职位不单独走技术移民；若持注册社工资格可按社工(Social Worker)评估。")]),

 dict(code="442111", en="Correctional Officer", zh="惩教官员（狱警）", cat=GOV, pub=1,
      wf=22000, growth=["Custodial Services", "Rehabilitation Programs", "Security Operations", "Offender Management"],
      sum_zh="惩教官员(狱警)在州/领地监狱负责在押人员的看管、安全与改造支持，由州惩教部门雇用，有结构化培训与轮班津贴，无需学位、入职后带薪培训，非技术移民职业。",
      sum_en="Correctional officers supervise inmates and maintain safety and rehabilitation in state prisons, employed by state corrective-services agencies; structured paid training, shift allowances and no degree required; not a skilled migration occupation.",
      fc="监狱人口与安全需求支撑稳定招聘，通过体能/心理评估并完成入职培训者即可上岗。",
      tr="路径：惩教官员→高级/主管→专职(危机/情报)；轮班、加班与津贴显著影响实际收入。",
      edu=[("无需学位 + 入职带薪培训", "数周~数月", 0, 0, "雇主提供"),
           ("体能 / 心理 / 背景审查", "数周", 0, 0, "录用前")],
      qual=[("惩教官员入职培训证书", "州惩教部门", "强制", 1),
            ("National Police Check / 体能评估", "各州", "强制", 1)],
      listings=[("各州 corrections 官网", 800, 1800, "州政府"), ("Seek", 600, 1400, "全国")],
      sal=[("初级（0-3年）", 65000, 80000, "含培训期"), ("中级（3-8年）", 80000, 95000, "含轮班津贴"), ("资深 / 主管", 95000, 115000, "含加班")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), **PR_NONMIG},
      fit=["心理素质稳定、能轮班作业者", "想要无需学位的稳定公职者"],
      unfit=["难以应对高压与冲突环境者", "排斥轮班/夜班者", "以技术移民为目标者"],
      faqs=[("salary", "惩教官员澳洲薪资多少？", "约 AUD $6.5万~$11.5万，轮班与加班津贴影响较大，各州差异明显。"),
            ("migration", "狱警能技术移民吗？", "不能，属于州政府本地公职，且多要求公民/永居与背景审查。")]),

 dict(code="599614", en="Housing Officer", zh="住房官员", cat=GOV, pub=1,
      wf=18000, growth=["Social & Public Housing", "Tenancy Management", "Homelessness Services", "Community Housing"],
      sum_zh="住房官员在州政府住房部门及社区住房机构管理社会/公共住房的租约、分配、维修协调与租户支持，是政府资助的稳定民生岗位，非技术移民职业。",
      sum_en="Housing officers manage social/public housing tenancies, allocations, maintenance coordination and tenant support in state housing departments and community housing providers; a stable government-funded role, not a skilled migration occupation.",
      fc="住房压力与社会住房投资推动稳定需求，具备租约管理与社区服务经验者更抢手。",
      tr="路径：住房官员→高级/团队主管→服务经理；处理复杂租户与合规经验决定发展。",
      edu=[("高中 / 社区服务相关证书（常见）", "0~1年", 0, 8000, "或相关经验")],
      qual=[("Certificate IV in Social Housing / Community Services（加分）", "TAFE/RTO", "非强制", 0),
            ("National Police Check", "各州", "强制", 1)],
      listings=[("I work for NSW / 各州", 800, 1800, "州政府"), ("Seek", 800, 1600, "全国")],
      sal=[("初级（0-3年）", 71000, 82000, "Entry"), ("中级（3-8年）", 82000, 95000, "Experienced"), ("资深 / 主管", 95000, 122000, "Senior")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["擅长沟通、个案与租约管理的人", "想从事民生类公职者"],
      unfit=["不擅处理租户纠纷与情绪者", "以技术移民为目标者"],
      faqs=[("salary", "住房官员薪资多少？", "约 AUD $7.1万~$12.2万，资深/主管更高。"),
            ("migration", "住房官员能技术移民吗？", "不能，属于本地公共部门岗位，不在技术移民清单上。")]),

 dict(code="511114", en="University Administrator", zh="高校行政人员", cat=GOV, pub=1,
      wf=80000, growth=["Higher Education Admin", "Student Services", "Research Administration", "Academic Governance"],
      sum_zh="高校行政人员在大学从事学生服务、课程与考务、研究管理、招生与治理支持等，多数公立大学属公共部门、福利稳定，按 HEW 等级定级，非技术移民职业。",
      sum_en="University administrators handle student services, course and exam administration, research management, admissions and governance support; most public universities are public-sector with stable benefits, graded by HEW levels; not a skilled migration occupation.",
      fc="高等教育规模与研究管理需求支撑稳定岗位，熟悉学生系统与研究合规者更具优势。",
      tr="路径：行政官员(HEW4–6)→协调/经理(HEW7–9)；专业方向(研究管理/学生服务)决定收入。",
      edu=[("相关本科（常见）", "3~4年", 20000, 45000, "多数岗位要求"),
           ("研究生学历（高等级岗加分）", "1~2年", 20000, 60000, "可选")],
      qual=[("相关学历", "认可大学", "入行基础", 0)],
      listings=[("大学官网 / Seek", 1500, 3500, "全国"), ("Indeed", 1000, 2200, "全国")],
      sal=[("初级 HEW4–5（0-3年）", 65000, 80000, "Entry"), ("中级 HEW6–7（3-8年）", 85000, 105000, "Experienced"), ("资深 HEW8–9", 105000, 140000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中高", 4), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["有学位、喜欢教育/研究环境的人", "擅长行政、协调与系统操作者"],
      unfit=["追求高薪或商业节奏者", "以技术移民为目标者"],
      faqs=[("salary", "高校行政人员薪资多少？", "约 AUD $6.5万~$14万(HEW4–9)，资深研究/治理岗更高。"),
            ("migration", "高校行政能技术移民吗？", "不能，属于本地行政岗，不在技术移民清单上。")]),

 dict(code="599615", en="Grants Officer", zh="拨款官员", cat=GOV, pub=1,
      wf=14000, growth=["Government Grants", "Funding Programs", "Acquittal & Compliance", "Community Funding"],
      sum_zh="拨款官员在政府与公共机构负责设计、评估、发放与监管资助项目(grants)，处理申请评审、合同与款项核销(acquittal)，是政策资金落地的关键岗，薪资中上、需求稳定，非技术移民职业。",
      sum_en="Grants officers design, assess, administer and acquit government funding programs — reviewing applications, managing agreements and compliance; a key role in delivering policy funding, well-paid and steady; not a skilled migration occupation.",
      fc="政府资助项目持续运作带动稳定需求，熟悉评审、合规与款项核销流程者更抢手。",
      tr="路径：拨款官员→高级/拨款协调→项目经理；财务、合规与评审经验决定收入。",
      edu=[("相关本科（常见）", "3~4年", 20000, 45000, "多数岗位要求")],
      qual=[("相关学历", "认可大学", "入行基础", 0),
            ("Australian Citizenship（多数岗）", "—", "多数岗强制", 0)],
      listings=[("APSjobs / 各州", 800, 1800, "政府"), ("Seek", 800, 1600, "全国")],
      sal=[("初级（0-3年）", 70000, 82000, "Entry"), ("中级（3-8年）", 82000, 100000, "Experienced"), ("资深 / 协调", 100000, 120000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["擅长评审、文书与合规的人", "细心、有财务意识者"],
      unfit=["不擅长流程与合规细节者", "以技术移民为目标者"],
      faqs=[("salary", "拨款官员薪资多少？", "约 AUD $7万~$12万，悉尼及高等级岗更高。"),
            ("migration", "拨款官员能技术移民吗？", "不能，属于政府本地岗，多要求公民身份。")]),

 dict(code="599616", en="Electoral Officer", zh="选举官员", cat=GOV, pub=1,
      wf=4000, growth=["AEC / State Electoral", "Election Delivery", "Electoral Integrity", "Voter Services"],
      sum_zh="选举官员在澳洲选举委员会(AEC)及各州选举机构负责选举的组织、登记、合规与选民服务，常设岗稳定、选举期另有大量临时岗，享公职福利(15.4% 退休金)，非技术移民职业。",
      sum_en="Electoral officers organise elections, manage enrolment, integrity and voter services at the AEC and state electoral commissions; permanent roles are stable with public-sector benefits, plus many casual roles during elections; not a skilled migration occupation.",
      fc="选举周期与选民登记工作支撑常设需求，选举期临时岗位大量增加。",
      tr="路径：选举官员→高级/项目→管理岗；选举交付与合规经验决定发展。",
      edu=[("高中 / 相关本科（视等级）", "0~4年", 0, 40000, "高等级岗需学位")],
      qual=[("Australian Citizenship", "—", "强制", 1),
            ("相关学历（按等级）", "认可机构", "高等级要求", 0)],
      listings=[("AEC / 各州选举机构", 200, 600, "常设+选举临时"), ("APSjobs", 200, 500, "联邦")],
      sal=[("初级（0-3年）", 65000, 77000, "Entry"), ("中级（3-8年）", 77000, 90000, "Experienced"), ("资深 / 管理", 90000, 110000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["注重流程、合规与公正者", "有公民身份、想进入公职者"],
      unfit=["排斥选举期高强度临时工作者", "以技术移民为目标者"],
      faqs=[("salary", "选举官员薪资多少？", "常设岗约 AUD $6.5万~$11万(+15.4% super)；选举期临时岗按时薪计。"),
            ("migration", "选举官员能技术移民吗？", "不能，且要求澳洲公民身份。")]),

 dict(code="599214", en="Court Clerk / Registry Officer", zh="法院书记 / 登记官员", cat=GOV, pub=1,
      wf=12000, growth=["Court Services", "Case Registry", "Digital Courts", "Judicial Support"],
      sum_zh="法院书记/登记官员在各级法院负责立案登记、排期、文书管理与庭审支持，是司法系统运行的基础公职岗，由各州司法部门或联邦法院雇用，稳定且有晋升路径，非技术移民职业。",
      sum_en="Court clerks / registry officers handle case registration, listings, document management and courtroom support across the court system; foundational public-sector roles in state justice departments and federal courts, stable with progression; not a skilled migration occupation.",
      fc="法院数字化与案件量支撑稳定需求，熟悉登记系统与司法流程者可向 registrar 方向发展。",
      tr="路径：登记官员→高级/Deputy Registrar→Registrar；司法流程与法律知识决定上限。",
      edu=[("高中 / 法律或相关证书(常见)", "0~3年", 0, 30000, "registrar 岗需更高学历")],
      qual=[("相关资质(按岗位)", "认可机构", "高等级要求", 0),
            ("National Police Check", "各州", "强制", 1)],
      listings=[("I work for NSW / 各州 / 联邦法院", 600, 1400, "政府"), ("Seek", 500, 1200, "全国")],
      sal=[("初级（0-3年）", 62000, 75000, "Entry"), ("中级（3-8年）", 75000, 90000, "Experienced"), ("资深 / Deputy Registrar", 90000, 115000, "Senior")],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["细心、注重流程与文书的人", "对司法系统有兴趣者"],
      unfit=["不擅长严谨流程与记录者", "以技术移民为目标者"],
      faqs=[("salary", "法院书记/登记官员薪资多少？", "约 AUD $6.2万~$11.5万，Deputy Registrar 等更高。"),
            ("migration", "法院书记能技术移民吗？", "不能，属于司法系统本地公职，不在技术移民清单上。")]),

 dict(code="224213", en="Health Information Manager", zh="健康信息管理师", cat=GOV, pub=1,
      wf=10000, growth=["Health Information Management", "Clinical Coding", "eHealth Records", "Data Governance"],
      sum_zh="健康信息管理师负责医院与卫生机构的病历信息、临床编码(ICD)、数据治理与隐私合规，多在公立医院系统(公共部门)工作，是专业化、薪资中上的健康行政岗，非技术移民职业(注：HIM 在部分清单上另有评估，本条按公立系统岗位呈现)。",
      sum_en="Health information managers oversee medical records, clinical coding (ICD), data governance and privacy compliance in hospitals and health services; a professional, well-paid health-admin role mostly in the public hospital system; presented here as a public-sector role.",
      fc="电子病历与数据治理推动专业化需求，持 HIM/临床编码资质者抢手且薪资走高。",
      tr="路径：HIM/编码员→高级→经理；临床编码、数据治理与系统经验决定收入。",
      edu=[("Health Information Management 相关本科", "3~4年", 20000, 45000, "专业岗要求"),
           ("临床编码(Clinical Coding)培训", "数月~1年", 2000, 12000, "编码岗要求")],
      qual=[("HIM 相关学历 / HIMAA 会员", "认可大学 / HIMAA", "专业基础", 0),
            ("Clinical Coding 资质", "HIMAA/认可机构", "编码岗要求", 0)],
      listings=[("Seek", 600, 1300, "全国"), ("各州 health 官网", 400, 900, "公立医院")],
      sal=[("初级 / 编码员（0-2年）", 65000, 80000, "Entry"), ("中级（3-7年）", 85000, 100000, "Experienced"), ("资深 / 经理", 110000, 140000, "Manager")],
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中等", 3), "income_level": ("中高", 4),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["细致、对医疗数据与编码有兴趣者", "想进入专业化健康行政岗者"],
      unfit=["不愿读相关专业者", "排斥严谨数据与合规工作者"],
      faqs=[("salary", "健康信息管理师薪资多少？", "约 AUD $6.5万~$14万，经理岗更高，临床编码资质加成明显。"),
            ("migration", "健康信息管理师能技术移民吗？", "Health Information Manager(224213)在部分技术移民清单上、有评估路径；具体以最新清单及评估机构为准。")]),

 dict(code="512112", en="Hospital Administration Officer", zh="医院行政官员", cat=GOV, pub=1,
      wf=70000, growth=["Public Hospital Admin", "Patient Administration", "Ward Clerk", "Health Service Support"],
      sum_zh="医院行政官员在公立医院负责患者登记、排期、病区文书、调度与一般行政支持，是公共卫生系统运行的基础岗，入职门槛较低、稳定且有内部晋升路径，非技术移民职业。",
      sum_en="Hospital administration officers handle patient registration, scheduling, ward clerking and general admin support in public hospitals; accessible, stable roles foundational to the public health system, with internal progression; not a skilled migration occupation.",
      fc="医疗系统扩张支撑稳定需求，熟悉医院系统与流程者可向 practice/health service 管理发展。",
      tr="路径：行政官员→高级/协调→服务管理；医院系统与调度经验决定发展。",
      edu=[("高中 / 健康行政相关证书（常见）", "0~1年", 0, 4000, "在岗培训为主")],
      qual=[("Certificate III/IV in Health Administration（加分）", "TAFE/RTO", "非强制", 0),
            ("National Police Check / 免疫要求", "各州", "强制", 1)],
      listings=[("各州 health 官网", 1500, 3000, "公立医院"), ("Seek", 1200, 2400, "全国")],
      sal=[("初级（0-3年）", 60000, 72000, "Entry"), ("中级（3-8年）", 75000, 95000, "Experienced"), ("资深 / 协调", 95000, 115000, "Senior")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("很短", 1), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("良好", 4), "ai_risk": ("中高", 4), **PR_NONMIG},
      fit=["细心、抗压、擅长多任务的人", "想进入公共卫生系统稳定岗者"],
      unfit=["不适应医院节奏与轮班者", "以技术移民为目标者"],
      faqs=[("salary", "医院行政官员薪资多少？", "约 AUD $6万~$11.5万，资深协调岗更高。"),
            ("migration", "医院行政能技术移民吗？", "不能，属于公共卫生系统本地行政岗，不在技术移民清单上。")]),

 dict(code="251312", en="Environmental Health Officer", zh="环境健康官员", cat=GOV, pub=1,
      wf=8000, growth=["Public Health Regulation", "Food Safety", "Environmental Compliance", "Council Health Services"],
      sum_zh="环境健康官员主要在地方议会与州卫生部门执行公共卫生法规：食品安全检查、水质与污染监管、传染病与卫生投诉处理，是政府监管类专业岗，薪资中上、需求稳定，非技术移民职业(注：EHO 在部分清单上另有评估)。",
      sum_en="Environmental health officers enforce public-health law mainly in local councils and state health departments — food safety inspections, water/pollution control and complaint handling; a professional government-regulatory role, well-paid and steady.",
      fc="食品安全与环境合规监管需求稳定，持认可 EHO 学历并注册者岗位充足。",
      tr="路径：EHO(graduate)→高级/Coordinator→Manager；专业注册与执法经验决定收入。",
      edu=[("环境健康相关本科(认可)", "3~4年", 20000, 45000, "专业岗强制"),
           ("各州 EHO 注册 / 任命", "数周", 0, 1000, "执法授权")],
      qual=[("认可 Environmental Health 学历", "认可大学", "专业基础", 1),
            ("各州环境健康官员注册/任命", "州卫生部门/议会", "执法要求", 0)],
      listings=[("council 官网 / Seek", 400, 900, "议会"), ("各州 health 官网", 200, 600, "州政府")],
      sal=[("初级 / Graduate（0-3年）", 75000, 88000, "Entry"), ("中级（3-8年）", 88000, 105000, "Experienced"), ("资深 / 协调", 105000, 135000, "Senior")],
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中等", 3), "income_level": ("中高", 4),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), **PR_NONMIG},
      fit=["对公共卫生与执法监管有兴趣者", "细致、擅长检查与报告的人"],
      unfit=["不愿读相关专业者", "排斥外勤检查与执法冲突者"],
      faqs=[("salary", "环境健康官员薪资多少？", "约 AUD $7.5万~$13.5万，资深/协调岗及大城市更高。"),
            ("migration", "环境健康官员能技术移民吗？", "Environmental Health Officer 在部分技术移民清单上、有评估路径；具体以最新清单及评估机构为准。")]),

 dict(code="451612", en="Transport / Station Officer", zh="交通 / 车站官员", cat=GOV, pub=1,
      wf=30000, growth=["Public Transport Ops", "Customer Safety", "Station Services", "Authorised Officer"],
      sum_zh="交通/车站官员在州公共交通系统(如 Sydney Trains、各州运输局)负责车站运营、乘客服务、安全巡查与票务合规(授权官员/Authorised Officer)，由政府运输机构雇用、有轮班津贴，是稳定的公共部门蓝领/服务岗，非技术移民职业。",
      sum_en="Transport / station officers run station operations, passenger service, safety patrols and fare compliance (authorised officers) in state public-transport systems; employed by government transport agencies with shift allowances; a stable public-sector role, not a skilled migration occupation.",
      fc="公共交通运营与安全需求支撑稳定招聘，轮班与津贴使实际收入高于基本工资。",
      tr="路径：车站官员→高级/值班经理→运营岗；授权官员资格与轮班经验影响收入。",
      edu=[("高中 + 入职带薪培训", "数周", 0, 0, "雇主提供"),
           ("Authorised Officer / 安全培训", "数周", 0, 500, "岗位要求")],
      qual=[("入职运营 / 授权官员培训", "州运输机构", "强制", 1),
            ("National Police Check", "各州", "强制", 1)],
      listings=[("各州 transport 官网", 600, 1400, "州政府"), ("Seek", 500, 1100, "全国")],
      sal=[("初级（0-3年）", 58000, 68000, "含培训期"), ("中级（3-8年）", 68000, 78000, "含轮班津贴"), ("资深 / 值班", 78000, 90000, "含加班")],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("很短", 1), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), **PR_NONMIG},
      fit=["能轮班、擅长乘客服务与安全处置者", "想要无需学位的稳定公职者"],
      unfit=["排斥夜班/轮班与户外作业者", "以技术移民为目标者"],
      faqs=[("salary", "交通/车站官员薪资多少？", "约 AUD $5.8万~$9万，轮班与加班津贴影响较大。"),
            ("migration", "车站官员能技术移民吗？", "不能，属于州政府公共交通本地岗，不在技术移民清单上。")]),
]


def run():
    ok = 0
    for o in OCCS:
        OCC = {
            "occ_code": o["code"], "anzsco_code": o["code"], "anzsco_title": o["en"],
            "category": o["cat"], "workforce_size": o["wf"],
            "shortage_listed": 0, "is_migration": 0, "is_public_servant": o.get("pub", 0),
            "growth_areas": json.dumps(o["growth"], ensure_ascii=False),
        }
        ZH = {"locale": "zh-CN", "name": o["zh"], "summary": o["sum_zh"],
              "forecast_note": o["fc"], "trend_summary": o["tr"]}
        EN = {"locale": "en", "name": o["en"], "summary": o["sum_en"],
              "forecast_note": o["fc"], "trend_summary": o["tr"]}
        sources = [{"source_name": s[0], "content": s[1], "url": s[2]} for s in (SRC_JSA, SRC_SEEK)]
        with get_cursor() as cur:
            seed_occupation_v2(cur, OCC, ZH, EN, EDU(o["edu"]), QUAL(o["qual"]),
                               LIST(o["listings"]), SAL(o["sal"]), [], R(o["rat"]),
                               o["fit"], o["unfit"], sources, FAQ(o["faqs"]))
        path = generate_md(o["code"])
        print(f"  [md] {o['zh']} -> {getattr(path, 'name', path)}")
        ok += 1
    print(f"[OK] 批量入库完成 {ok}/{len(OCCS)}")


if __name__ == "__main__":
    run()
