# -*- coding: utf-8 -*-
"""澳洲(AU) 能源电力 + 半导体/电子 11 个新兴细分工程岗数据入库。

数据来源：SEEK / Indeed AU / Glassdoor AU / Jora / ERI SalaryExpert / PayScale（2025-2026）。
评分为 10 分制（对齐 DB 现有口径，seed_occupation_v2 直插不做换算）。

occ_code 采用唯一合成码（父级 ANZSCO + 后缀），仅用于幂等/消歧，页面只展示 anzsco_code；
避免与既有 233311(Electrical Engineer,id39)/233411 等行覆盖冲突。

运行：PYTHONIOENCODING=utf-8 python -m scripts.seed_energy_semiconductor_au
"""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.connection import get_cursor
from scripts._seed_helper import seed_occupation_v2

# —— 工程师岗共用澳洲技术/雇主担保签证路径（电气 233311 / 电子 233411 / 软件 261313 均在 CSOL/MLTSSL）——
VISA_ENG = [
    {"visa_subclass": "482", "visa_name": "Skills in Demand (SID)", "description": "雇主担保临居；能源/电网/数据中心/半导体企业担保紧缺工程师", "sort_order": 0},
    {"visa_subclass": "186", "visa_name": "ENS 雇主提名", "description": "雇主担保永居（Direct Entry / TRT 通道）", "sort_order": 1},
    {"visa_subclass": "189", "visa_name": "技术独立", "description": "邀请制独立技术移民；需 Engineers Australia 职业评估（CDR 或认可学历）", "sort_order": 2},
    {"visa_subclass": "190", "visa_name": "州/领地提名", "description": "州提名加 5 分；工程类为多数州紧缺清单常客", "sort_order": 3},
    {"visa_subclass": "491", "visa_name": "偏远地区担保", "description": "偏远地区州提名/亲属担保临居，满足条件后转 191 永居", "sort_order": 4},
]
# 技术员/受限岗签证（EV 电池诊断）
VISA_TECH = [
    {"visa_subclass": "482", "visa_name": "Skills in Demand (SID)", "description": "雇主担保；EV/电池维保企业担保为主要通道", "sort_order": 0},
    {"visa_subclass": "186", "visa_name": "ENS 雇主提名", "description": "雇主担保永居，需 2~3 年担保经验", "sort_order": 1},
    {"visa_subclass": "491", "visa_name": "偏远地区担保", "description": "偏远地区提名，技术员岗更依赖此通道", "sort_order": 2},
]


def R(dim, label, stars, note):
    return {"dimension": dim, "label_zh": label, "stars": stars, "note": note}


ROLES = [
    # ============================ 1. Power Systems Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233311-PWR", "occ_code_type": "ANZSCO", "anzsco_code": "233311",
                "anzsco_title": "Power Systems Engineer", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 8000, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["可再生能源并网（风光大规模接入电网）", "输配电网规划与潮流/稳定性分析", "电网调度与 AEMO 市场建模", "储能与虚拟电厂(VPP)接入", "电网数字化与实时仿真(RTDS/DIgSILENT)"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "电力系统工程师",
               "summary": "电力系统工程师负责发电、输电、配电网络的规划、分析与运行，做潮流计算、短路与稳定性分析、保护整定和并网研究。澳洲能源转型（燃煤退役、风光储大规模并网）使该岗成为电力行业最紧缺的核心工程角色之一，广泛就业于电网公司、AEMO、可再生能源开发商和工程咨询公司。",
               "forecast_note": "澳洲 2030 年可再生能源占比目标 82%，叠加燃煤机组退役与电网升级（Rewiring the Nation 200 亿澳元计划），Jobs and Skills Australia 将电气工程列为长期紧缺。电力系统工程师需求预计 2025-2035 保持两位数增长，资深并网/稳定性专家供不应求。",
               "trend_summary": "2026 年风光储项目排队并网、电网调度复杂度激增，掌握 PSS/E、DIgSILENT PowerFactory、PSCAD 的并网研究工程师最抢手。AI 辅助潮流与故障分析，但电网安全稳定的责任判断仍由持证工程师承担，AI 替代风险低。"},
        "EN": {"locale": "en", "name": "Power Systems Engineer",
               "summary": "Power systems engineers plan, analyse and operate generation, transmission and distribution networks — running load-flow, short-circuit and stability studies, protection settings and grid-connection studies. Australia's energy transition (coal retirement plus large-scale wind/solar/storage integration) has made this one of the most in-demand core engineering roles, employed by network operators, AEMO, renewable developers and consultancies.",
               "forecast_note": "With an 82% renewables target by 2030, coal plant retirements and the A$20bn Rewiring the Nation program, Jobs and Skills Australia lists electrical engineering as a persistent shortage. Demand for power systems engineers is projected to grow double-digits through 2025-2035, with senior grid-connection/stability specialists in short supply.",
               "trend_summary": "In 2026, grid-connection queues and rising dispatch complexity make engineers skilled in PSS/E, DIgSILENT PowerFactory and PSCAD the most sought-after. AI assists load-flow and fault analysis, but accountability for grid security stays with chartered engineers, keeping AI replacement risk low."},
        "EDU": [
            {"stage": "Bachelor of Electrical/Power Engineering（电气/电力工程学士，4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "电力系统方向硕士 / 并网仿真专项培训（PSS/E、PowerFactory）", "duration": "1~2 年", "cost_min": 30000, "cost_max": 90000, "cost_note": "提升并网研究与稳定性分析竞争力", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估 / CPEng 特许工程师", "duration": "3~6 个月评估；CPEng 数年", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民职业评估必须；CPEng/NER 提升执业与薪资", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电气工程学位（Engineers Australia / 华盛顿协议）", "issuer": "Engineers Australia", "note": "执业与技术移民职业评估的基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "CPEng（Chartered Professional Engineer）/ NER 注册", "issuer": "Engineers Australia", "note": "资深职位与咨询签字权常要求", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "并网/稳定性仿真软件能力（PSS/E、DIgSILENT、PSCAD）", "issuer": "厂商/项目实践", "note": "并网研究岗的核心竞争力", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 300, "count_max": 900, "note": "全国，含电力系统/并网/保护/电网规划工程师"},
            {"platform": "Indeed", "count_min": 200, "count_max": 600, "note": "含电网公司、AEMO、可再生能源开发商岗"},
            {"platform": "LinkedIn", "count_min": 400, "count_max": 1000, "note": "咨询公司(AECOM/GHD/Aurecon)与开发商直招活跃"},
        ],
        "SAL": [
            {"experience": "毕业/初级（0~3 年）", "salary_min": 85000, "salary_max": 110000, "salary_note": "Glassdoor 均值约 $110k；起薪随电网/咨询公司", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 110000, "salary_max": 150000, "salary_note": "Jora/SEEK 广告均值约 $135k；墨尔本约 $140k", "sort_order": 1},
            {"experience": "资深/主任（8 年+）", "salary_min": 150000, "salary_max": 200000, "salary_note": "ERI 均值约 $158k；Senior 约 $154k，专家可达 $194k+", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "电气工程学位 + 电力系统专业方向，数理与仿真要求高"),
            R("learning_duration", "长", 8, "4 年学位 + 数年并网/稳定性经验积累"),
            R("certification_difficulty", "中等", 6, "职业评估必需；CPEng/NER 为进阶"),
            R("job_demand", "极高", 9, "能源转型驱动，Jobs and Skills Australia 长期紧缺"),
            R("competition", "低", 4, "技能短缺，资深并网工程师供不应求"),
            R("work_intensity", "中等", 6, "项目周期与并网节点压力，偶有现场/调度值守"),
            R("income_level", "较高", 8, "$110k~$160k，资深/专家 $200k+"),
            R("future_prospect", "极好", 10, "电网转型十年以上长周期需求"),
            R("ai_risk", "低", 3, "AI 辅助分析，但电网安全责任判断不可替代"),
            R("pr_friendliness", "高", 9, "电气工程在 CSOL/MLTSSL，189/190/482→186 通畅"),
            R("pr_difficulty", "低", 4, "紧缺职业，技术移民相对容易"),
        ],
        "FIT": ["电气/电力工程背景，愿深耕并网、稳定性或电网规划方向", "掌握或愿学 PSS/E、DIgSILENT PowerFactory、PSCAD 等仿真工具", "希望进入澳洲能源转型长期增长赛道并走技术移民", "细致、责任心强，能承担电网安全相关的工程判断"],
        "UNFIT": ["数理/电路基础薄弱且不愿投入长期学习", "排斥法规、标准与安全合规为核心的工程工作", "期望短期速成高薪、不接受多年经验积累"],
        "SOURCES": [
            {"source_name": "Glassdoor AU", "content": "Power Systems Engineer 均值约 $110k；Senior 约 $154k", "url": "https://www.glassdoor.com.au/Salaries/power-systems-engineer-salary-SRCH_KO0,22.htm"},
            {"source_name": "Jora / SEEK AU", "content": "广告薪资均值约 $135k；墨尔本约 $140k", "url": "https://au.jora.com/s/Power-Systems-Engineer-salary"},
            {"source_name": "ERI SalaryExpert", "content": "均值约 $158,869；区间 $109k~$194k", "url": "https://www.erieri.com/salary/job/power-systems-engineer/australia"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲电力系统工程师工资多少？", "answer": "初级约 $85k~$110k；中级 $110k~$150k（广告均值约 $135k）；资深/专家 $150k~$200k+（ERI 均值约 $158k）。并网研究与稳定性专家溢价最高。"},
            {"faq_type": "demand", "sort_order": 1, "question": "这个岗位在澳洲好找工作吗？", "answer": "很好。能源转型（82% 可再生目标、燃煤退役、Rewiring the Nation）使电气工程长期紧缺，SEEK 常年数百个相关岗位，电网公司、AEMO、开发商和咨询公司持续招聘。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外电力工程学历澳洲认可吗？", "answer": "需通过 Engineers Australia 职业评估（华盛顿协议认可学位可走认证通道，否则提交 CDR）。评估通过后即可用于 189/190 技术移民及执业。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "电力系统工程师会被 AI 替代吗？", "answer": "风险低。AI 加速潮流、故障和场景分析，但电网安全稳定的责任判断、并网合规签字仍由持证工程师承担，AI 是增强而非替代。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "电力系统工程师能技术移民吗？", "answer": "能。电气工程（233311 家族）在 CSOL/MLTSSL，可走 189 独立、190 州提名或 482→186 雇主担保，属紧缺职业，路径通畅。"},
        ],
    },
    # ============================ 2. BESS / Battery Energy Storage Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233311-BESS", "occ_code_type": "ANZSCO", "anzsco_code": "233311",
                "anzsco_title": "Battery Energy Storage (BESS) Engineer", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 2000, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["电网级储能电站(Grid-scale BESS)设计与并网", "储能系统集成(PCS/EMS/BMS)与调试", "储能安全与消防合规(AS/IEC 标准)", "虚拟电厂(VPP)与户用储能聚合", "储能项目并网研究与市场套利建模"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "储能系统工程师",
               "summary": "储能系统工程师负责电池储能电站(BESS)的电气设计、系统集成、并网与调试，涵盖 PCS 变流器、EMS 能量管理、BMS 电池管理与安全消防合规。澳洲电网级储能进入爆发期（多个 GWh 级项目在建），是能源领域增长最快、供给最紧缺的工程岗之一。",
               "forecast_note": "澳洲电网级储能装机 2025-2030 预计翻数倍，联邦与各州储能激励叠加燃煤退役，Jobs and Skills Australia 将相关电气/能源工程列为紧缺。既懂电力电子又懂并网合规的储能工程师薪资溢价明显。",
               "trend_summary": "2026 年大型 BESS 项目排队并网，储能安全标准(AS/NZS、IEC 62933)与消防设计成为招聘硬门槛。AI 优化调度与套利策略，但电气设计、安全合规与调试仍高度依赖人，AI 替代风险低。"},
        "EN": {"locale": "en", "name": "Battery Energy Storage (BESS) Engineer",
               "summary": "BESS engineers handle electrical design, system integration, grid connection and commissioning of battery energy storage systems — covering PCS inverters, EMS energy management, BMS and fire/safety compliance. Australia's grid-scale storage is booming (multiple GWh-scale projects under construction), making this one of the fastest-growing and most supply-constrained engineering roles in the energy sector.",
               "forecast_note": "Australia's grid-scale storage capacity is expected to multiply over 2025-2030; federal and state storage incentives plus coal retirements keep related electrical/energy engineering in shortage. Engineers who combine power-electronics and grid-connection compliance command a clear salary premium.",
               "trend_summary": "In 2026, large BESS projects queue for connection, and storage safety standards (AS/NZS, IEC 62933) and fire design have become hard hiring requirements. AI optimises dispatch and arbitrage, but electrical design, safety compliance and commissioning stay human-led — keeping AI replacement risk low."},
        "EDU": [
            {"stage": "电气/机电/能源工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "电力电子/储能系统专项（PCS、BMS、EMS）", "duration": "6~18 个月", "cost_min": 3000, "cost_max": 40000, "cost_note": "厂商培训或硕士方向，储能集成核心能力", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电气/机电工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "储能安全/并网标准知识（AS/NZS、IEC 62933）", "issuer": "标准机构/项目实践", "note": "储能设计与合规硬门槛", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "CPEng / 高压作业相关资质", "issuer": "Engineers Australia / 各州", "note": "现场调试与资深岗常要求", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 150, "count_max": 500, "note": "含储能/BESS/能源存储工程师岗（能源存储类目）"},
            {"platform": "Indeed", "count_min": 100, "count_max": 350, "note": "开发商、EPC、逆变器/储能厂商岗"},
            {"platform": "Glassdoor", "count_min": 120, "count_max": 300, "note": "电池/储能工程师岗，约 $130k~$164k"},
        ],
        "SAL": [
            {"experience": "初级（0~3 年）", "salary_min": 95000, "salary_max": 120000, "salary_note": "Indeed 区间约 $129k 起（含 12% super）", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 120000, "salary_max": 160000, "salary_note": "Glassdoor 区间 $130k~$164k", "sort_order": 1},
            {"experience": "资深/主任（8 年+）", "salary_min": 160000, "salary_max": 200000, "salary_note": "并网/系统集成专家，含项目津贴", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "电气 + 电力电子 + 储能安全合规综合要求高"),
            R("learning_duration", "长", 8, "4 年学位 + 储能项目集成经验"),
            R("certification_difficulty", "中等", 6, "职业评估 + 储能标准知识"),
            R("job_demand", "极高", 9, "电网级储能爆发，供给严重不足"),
            R("competition", "极低", 3, "既懂电力电子又懂并网的人才稀缺"),
            R("work_intensity", "中等", 6, "调试/并网节点强度较高，含现场"),
            R("income_level", "较高", 8, "$120k~$164k，资深 $200k"),
            R("future_prospect", "极好", 10, "储能十年高速增长赛道"),
            R("ai_risk", "低", 3, "AI 优化调度，电气设计与安全合规不可替代"),
            R("pr_friendliness", "高", 9, "电气工程在紧缺清单"),
            R("pr_difficulty", "低", 4, "紧缺职业，移民相对容易"),
        ],
        "FIT": ["电气/机电背景，想进入储能这一高增长新兴赛道", "对电力电子(PCS/逆变器)、BMS/EMS 或并网合规有兴趣", "愿意参与现场调试与并网，接受一定出差", "希望走技术移民并绑定能源转型长期需求"],
        "UNFIT": ["只想纯办公室、排斥现场调试与出差", "不愿学习储能安全/消防标准等合规内容", "电路与电力电子基础薄弱且无补强意愿"],
        "SOURCES": [
            {"source_name": "Glassdoor AU", "content": "Battery Engineer AU 区间 $130k~$164k", "url": "https://www.glassdoor.com.au/Job/australia-battery-engineer-jobs-SRCH_IL.0,9_KO10,26.htm"},
            {"source_name": "Indeed AU", "content": "储能/电池工程师区间约 $129k~$143k + 12% super", "url": "https://au.indeed.com/q-australia-battery-engineer-jobs.html"},
            {"source_name": "SEEK AU", "content": "能源存储(Energy Storage)类目在招储能工程师", "url": "https://www.seek.com.au/energy-storage-jobs"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲储能系统工程师工资多少？", "answer": "初级约 $95k~$120k；中级 $120k~$160k（Glassdoor $130k~$164k）；资深 $160k~$200k。Indeed 显示常含 12% 养老金与年假补贴。"},
            {"faq_type": "demand", "sort_order": 1, "question": "储能工程师在澳洲需求大吗？", "answer": "非常大。澳洲电网级储能进入爆发期，多个 GWh 级项目在建，既懂电力电子又懂并网合规的工程师严重供不应求。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外储能/电气经验澳洲认可吗？", "answer": "电气工程学历需经 Engineers Australia 评估；储能项目经验（PCS/BMS/并网/AS-IEC 标准）是直接加分项，开发商和 EPC 会优先录用有实战经验者。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "储能工程师会被 AI 替代吗？", "answer": "风险低。AI 优化充放电调度与市场套利，但电气设计、安全消防合规和现场调试高度依赖工程师，属 AI 增强型岗位。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "储能系统工程师能移民吗？", "answer": "能。归入电气工程(233311 家族)紧缺职业，可走 189/190 或 482→186，储能经验使雇主担保意愿更强。"},
        ],
    },
    # ============================ 3. EV Charging Infrastructure Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233311-EVCI", "occ_code_type": "ANZSCO", "anzsco_code": "233311",
                "anzsco_title": "EV Charging Infrastructure Engineer", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 1500, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["公共快充/超充站(DCFC)电气设计与并网", "充电网络负荷管理与配电升级", "充电桩标准与合规(AS/NZS 3000、OCPP)", "车网互动(V2G)与站点储能集成", "车队与商用充电基础设施规划"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "电动车充电基础设施工程师",
               "summary": "电动车充电基础设施工程师负责公共/商用充电站的电气设计、配电接入、并网与合规，涵盖直流快充(DCFC)、负荷管理、OCPP 通信与场站储能集成。随着澳洲 EV 保有量快速上升与充电网络铺设，该岗从电气工程中快速分化、需求上行。",
               "forecast_note": "澳洲联邦与各州充电网络资助持续投入，EV 渗透率上升推动公共快充与车队充电大规模建设，电气工程整体紧缺使充电基础设施方向招聘活跃，中长期前景良好。",
               "trend_summary": "2026 年超充站(350kW+)与车队充电成为热点，站点常需配电升级与储能削峰，懂并网与负荷管理的工程师最吃香。AI 辅助选址与负荷预测，核心电气设计与合规仍由工程师完成。"},
        "EN": {"locale": "en", "name": "EV Charging Infrastructure Engineer",
               "summary": "EV charging infrastructure engineers handle electrical design, grid/distribution connection, and compliance for public and commercial charging stations — covering DC fast charging (DCFC), load management, OCPP communications and on-site storage integration. As Australia's EV fleet grows and charging networks roll out, this role is rapidly branching off from electrical engineering with rising demand.",
               "forecast_note": "Sustained federal and state charging-network funding plus rising EV penetration drive large-scale public fast-charging and fleet-charging build-out. Broad electrical-engineering shortage keeps hiring active, with a solid medium-to-long-term outlook.",
               "trend_summary": "In 2026, ultra-fast (350kW+) and fleet charging are hotspots; sites often need distribution upgrades and storage for peak shaving, so engineers skilled in grid connection and load management are prized. AI assists siting and load forecasting, but core electrical design and compliance stay human-led."},
        "EDU": [
            {"stage": "电气工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "充电/配电与并网专项（OCPP、AS/NZS 3000）", "duration": "3~12 个月", "cost_min": 2000, "cost_max": 20000, "cost_note": "充电标准与配电接入实操能力", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电气工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "充电与配电标准（AS/NZS 3000、OCPP、EVSE 规范）", "issuer": "标准机构/厂商", "note": "充电站设计合规核心", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "CPEng / 电工执照（视职责）", "issuer": "Engineers Australia / 各州", "note": "现场与资深岗常要求", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 150, "count_max": 500, "note": "EV/充电/电气岗，含充电网络运营商与 EPC"},
            {"platform": "Indeed", "count_min": 100, "count_max": 300, "note": "含 EV 充电与电气基础设施岗"},
            {"platform": "LinkedIn", "count_min": 150, "count_max": 400, "note": "充电网络(Evie/Chargefox/BP Pulse 等)与工程咨询直招"},
        ],
        "SAL": [
            {"experience": "初级（0~3 年）", "salary_min": 80000, "salary_max": 105000, "salary_note": "电气工程起薪，参考电子/电气工程均值", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 105000, "salary_max": 140000, "salary_note": "电气工程师中级区间", "sort_order": 1},
            {"experience": "资深/项目（8 年+）", "salary_min": 140000, "salary_max": 175000, "salary_note": "充电网络/电气项目经理 $130k~$175k", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "较高", 7, "电气工程 + 充电/配电标准与并网知识"),
            R("learning_duration", "较长", 7, "4 年学位 + 充电基础设施项目经验"),
            R("certification_difficulty", "中等", 6, "职业评估 + 充电/配电标准"),
            R("job_demand", "高", 8, "EV 渗透与充电网络铺设推动需求上行"),
            R("competition", "低", 4, "电气工程短缺，充电方向人才有限"),
            R("work_intensity", "中等", 6, "含现场勘查、并网与调试"),
            R("income_level", "中高", 7, "$90k~$140k，项目/资深 $175k"),
            R("future_prospect", "很好", 9, "EV 与充电网络长期扩张"),
            R("ai_risk", "低", 3, "AI 辅助选址/负荷预测，电气设计与合规不可替代"),
            R("pr_friendliness", "高", 8, "电气工程紧缺清单"),
            R("pr_difficulty", "中低", 5, "紧缺职业，移民较易"),
        ],
        "FIT": ["电气工程背景，想切入 EV 与充电基础设施新赛道", "对配电接入、负荷管理、充电标准(OCPP/AS-NZS)感兴趣", "愿意做现场勘查与并网调试", "看重 EV 长期增长趋势并考虑技术移民"],
        "UNFIT": ["不愿接触现场与配电工程、只想纯软件", "排斥标准合规与安全规范工作", "电气基础薄弱且无补强计划"],
        "SOURCES": [
            {"source_name": "Pathway to Aus", "content": "EV 相关工程岗薪资指南（2026），充电/电气方向", "url": "https://pathwaytoaus.com/general/electric-vehicle-jobs-in-australia-salary-guide-2026/"},
            {"source_name": "SEEK AU", "content": "EV 类目在招充电与电气基础设施岗", "url": "https://www.seek.com.au/ev-jobs"},
            {"source_name": "CDR for Australia", "content": "电子/电气工程师均值 $95k+，随专业与经验上升", "url": "https://cdrforaustralia.com/electronics-engineer-in-australia/"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲电动车充电基础设施工程师工资多少？", "answer": "初级约 $80k~$105k；中级 $105k~$140k；资深/项目经理 $140k~$175k。绑定电气工程薪酬体系，充电网络与快充项目溢价较好。"},
            {"faq_type": "demand", "sort_order": 1, "question": "充电基础设施工程师好找工作吗？", "answer": "较好且上行。EV 渗透率上升、充电网络与车队充电大规模铺设，叠加电气工程整体短缺，充电运营商、EPC 和咨询公司持续招聘。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外电气/充电经验澳洲认可吗？", "answer": "电气学历经 Engineers Australia 评估；充电站设计、配电接入、OCPP 与 AS/NZS 合规经验是直接加分项。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "这个岗会被 AI 替代吗？", "answer": "风险低。AI 辅助选址与负荷预测，但充电站电气设计、并网与安全合规由工程师负责，属增强型岗位。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。归入电气工程(233311 家族)紧缺职业，189/190/482→186 均可，充电专业经验增强雇主担保意愿。"},
        ],
    },
    # ============================ 4. Data Centre Electrical Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233311-DCE", "occ_code_type": "ANZSCO", "anzsco_code": "233311",
                "anzsco_title": "Data Centre Electrical Engineer", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 3000, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["超大规模/AI 数据中心供电设计(MV/LV)", "关键供电冗余(UPS/发电机/2N)与可靠性", "液冷/高密度机柜供电与散热配合", "数据中心并网与容量规划", "运维关键设施(Critical Facilities)电气工程"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "数据中心电气工程师",
               "summary": "数据中心电气工程师负责数据中心的供配电系统设计与运维，涵盖中低压配电、UPS 与发电机冗余、2N 架构可靠性、高密度/液冷机柜供电与容量规划。AI 算力需求引爆澳洲数据中心建设，该岗成为电气工程中薪资与需求都极高的方向。",
               "forecast_note": "APAC 数据中心建设投资高速增长（多份报告预计 2028 年市场规模显著扩大），悉尼、墨尔本超大规模园区密集落地，AI 算力叠加电力需求，使关键设施电气工程师长期极度紧缺。",
               "trend_summary": "2026 年 AI 数据中心以百 MW 级供电与液冷高密度为特征，2N 冗余、并网容量和可靠性设计是核心。运维侧常需 24/7 关键设施值守，AI 辅助监控但供电可靠性责任由工程师承担。"},
        "EN": {"locale": "en", "name": "Data Centre Electrical Engineer",
               "summary": "Data centre electrical engineers design and operate power distribution — MV/LV distribution, UPS and generator redundancy, 2N reliability, high-density/liquid-cooled rack power and capacity planning. AI compute demand has ignited Australian data-centre construction, making this one of the highest-paid and most in-demand electrical-engineering specialisations.",
               "forecast_note": "APAC data-centre construction investment is growing fast (reports project a materially larger market by 2028); hyperscale campuses cluster in Sydney and Melbourne. AI compute plus electricity demand keep critical-facilities electrical engineers in severe long-term shortage.",
               "trend_summary": "In 2026, AI data centres feature hundred-MW power and high-density liquid cooling; 2N redundancy, connection capacity and reliability design are core. Operations often need 24/7 critical-facilities cover; AI assists monitoring but power-reliability accountability stays with engineers."},
        "EDU": [
            {"stage": "电气工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "关键设施/数据中心供电专项（UPS、发电机、2N、Uptime Tier）", "duration": "3~12 个月", "cost_min": 2000, "cost_max": 25000, "cost_note": "关键供电可靠性设计能力", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估 / CPEng", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "移民必须；CPEng 提升资深岗", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电气工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "关键设施可靠性/Uptime Tier 知识", "issuer": "行业/项目实践", "note": "数据中心供电设计核心", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "CPEng / 高压作业资质", "issuer": "Engineers Australia / 各州", "note": "资深设计与运维岗常要求", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 200, "count_max": 600, "note": "数据中心/关键设施电气岗，悉尼墨尔本集中"},
            {"platform": "Indeed", "count_min": 100, "count_max": 400, "note": "含超大规模运营商、EPC 与设计咨询"},
            {"platform": "LinkedIn", "count_min": 200, "count_max": 600, "note": "NEXTDC/AirTrunk/Equinix 等运营商直招活跃"},
        ],
        "SAL": [
            {"experience": "初级（0~3 年）", "salary_min": 100000, "salary_max": 130000, "salary_note": "数据中心方向起薪高于一般电气", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 130000, "salary_max": 170000, "salary_note": "数据中心工程师悉尼约 $139k，NSW 约 $155k", "sort_order": 1},
            {"experience": "资深/关键设施（8 年+）", "salary_min": 170000, "salary_max": 220000, "salary_note": "均值约 $160k，资深关键设施 $200k+", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "供配电 + 关键可靠性 + 高密度散热配合"),
            R("learning_duration", "长", 8, "4 年学位 + 关键设施项目经验"),
            R("certification_difficulty", "中等", 6, "职业评估 + Tier/可靠性知识"),
            R("job_demand", "极高", 10, "AI 算力引爆数据中心建设，供不应求"),
            R("competition", "极低", 3, "关键设施电气人才极稀缺"),
            R("work_intensity", "较高", 7, "关键设施 24/7，项目节点紧"),
            R("income_level", "高", 9, "$130k~$200k，资深关键设施最高"),
            R("future_prospect", "极好", 10, "AI 与云长期驱动"),
            R("ai_risk", "低", 3, "AI 辅助监控，供电可靠性责任不可替代"),
            R("pr_friendliness", "高", 9, "电气工程紧缺清单"),
            R("pr_difficulty", "低", 4, "极紧缺，移民相对容易"),
        ],
        "FIT": ["电气工程背景，想进入高薪的数据中心/关键设施赛道", "对供配电冗余、UPS/发电机、2N 可靠性设计感兴趣", "能接受关键设施 24/7 值守或较高项目强度", "看重 AI 算力驱动的长期需求并考虑移民"],
        "UNFIT": ["无法接受关键设施值守或高压项目节奏", "对供配电与可靠性工程不感兴趣", "电气基础薄弱且无补强意愿"],
        "SOURCES": [
            {"source_name": "Jora AU", "content": "Data Centre Engineer 澳洲均值约 $160k；悉尼约 $139k；NSW 约 $155k", "url": "https://au.jora.com/s/Data-Centre-Engineer-salary"},
            {"source_name": "Glassdoor AU", "content": "Data Centre Engineer 薪资趋势（2026）", "url": "https://www.glassdoor.com.au/Salaries/data-centre-engineer-salary-SRCH_KO0,20.htm"},
            {"source_name": "Mission Critical Recruit", "content": "APAC 数据中心建设高速增长，关键设施用工需求激增", "url": "https://www.missioncriticalrecruit.com/know-an-electrical-trade-why-a-data-centre-job-could-be-your-perfect-match"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲数据中心电气工程师工资多少？", "answer": "初级约 $100k~$130k；中级 $130k~$170k（悉尼约 $139k、NSW 约 $155k）；资深关键设施 $170k~$220k。是电气工程中最高薪方向之一。"},
            {"faq_type": "demand", "sort_order": 1, "question": "数据中心电气工程师需求怎样？", "answer": "极高。AI 算力引爆数据中心建设，悉尼墨尔本超大规模园区密集落地，关键设施电气人才严重供不应求。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外经验澳洲认可吗？", "answer": "电气学历经 Engineers Australia 评估；UPS/发电机/2N 冗余、Uptime Tier 与关键设施运维经验是直接加分项，运营商乐于担保。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险低。AI 辅助监控与能效优化，但供电可靠性设计与关键设施责任由工程师承担，属增强型岗位。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电气工程(233311 家族)紧缺，189/190/482→186 通畅，关键设施经验使雇主担保意愿强。"},
        ],
    },
    # ============================ 5. Protection & Control Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233311-PNC", "occ_code_type": "ANZSCO", "anzsco_code": "233311",
                "anzsco_title": "Protection & Control Engineer", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 3500, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["变电站保护整定与继电保护(IEC 61850)", "SCADA/自动化与二次系统设计", "可再生并网保护与孤岛检测", "储能/换流站保护与控制", "保护系统调试与现场投运"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "保护与控制工程师",
               "summary": "保护与控制工程师负责电网变电站的继电保护整定、二次系统与自动化设计、SCADA 与 IEC 61850 通信、以及保护系统调试投运，是保障电网安全稳定运行的关键角色。可再生并网与储能/换流站增多，使保护与控制专业需求持续上升。",
               "forecast_note": "电网升级、可再生大规模并网与储能/换流站建设推高保护与控制专业需求，Jobs and Skills Australia 将电气工程列为紧缺，资深继电保护与调试工程师尤为稀缺。",
               "trend_summary": "2026 年 IEC 61850 数字化变电站、并网保护与孤岛检测成为重点，懂保护整定与现场调试的工程师供不应求。AI 辅助整定校核，但保护逻辑与安全责任由持证工程师承担。"},
        "EN": {"locale": "en", "name": "Protection & Control Engineer",
               "summary": "Protection & control engineers handle substation relay protection settings, secondary/automation design, SCADA and IEC 61850 communications, and protection commissioning — a role critical to safe, stable grid operation. Growth in renewable connection and storage/converter stations keeps demand for protection & control specialists rising.",
               "forecast_note": "Grid upgrades, large-scale renewable integration and storage/converter-station build-out push up demand for protection & control specialists. Jobs and Skills Australia lists electrical engineering as a shortage, with senior relay-protection and commissioning engineers especially scarce.",
               "trend_summary": "In 2026, IEC 61850 digital substations, connection protection and islanding detection are focal points; engineers skilled in protection settings and field commissioning are in short supply. AI assists settings checks, but protection logic and safety accountability stay with chartered engineers."},
        "EDU": [
            {"stage": "电气/电力工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "继电保护/二次系统专项（IEC 61850、SCADA）", "duration": "6~18 个月", "cost_min": 3000, "cost_max": 30000, "cost_note": "保护整定与调试核心能力", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估 / CPEng", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "移民必须；CPEng 提升资深岗", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电气工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "继电保护/IEC 61850/SCADA 能力", "issuer": "厂商/项目实践", "note": "保护与控制岗核心竞争力", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "CPEng / 高压作业与调试资质", "issuer": "Engineers Australia / 各州", "note": "现场调试与资深岗常要求", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 150, "count_max": 500, "note": "保护/控制/二次/继电保护工程师岗"},
            {"platform": "Indeed", "count_min": 100, "count_max": 350, "note": "电网公司、咨询与 EPC 岗"},
            {"platform": "LinkedIn", "count_min": 200, "count_max": 500, "note": "电网(Transgrid/Powerlink 等)与咨询直招"},
        ],
        "SAL": [
            {"experience": "初级（0~3 年）", "salary_min": 90000, "salary_max": 115000, "salary_note": "参考电气工程与 P&C 起薪", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 115000, "salary_max": 155000, "salary_note": "P&C 工程师约 $110k~$122k，经验上升更高", "sort_order": 1},
            {"experience": "资深/主任（8 年+）", "salary_min": 155000, "salary_max": 195000, "salary_note": "资深继电保护/调试专家，含现场津贴", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "继电保护逻辑 + 二次系统 + 通信标准要求高"),
            R("learning_duration", "长", 8, "4 年学位 + 保护整定与调试经验"),
            R("certification_difficulty", "中等", 6, "职业评估 + 保护/自动化专业能力"),
            R("job_demand", "高", 8, "并网与储能推动，资深调试稀缺"),
            R("competition", "低", 4, "保护整定与现场调试人才有限"),
            R("work_intensity", "中等", 6, "含变电站现场调试与投运"),
            R("income_level", "较高", 8, "$115k~$155k，资深 $195k"),
            R("future_prospect", "很好", 9, "电网数字化与并网长期需求"),
            R("ai_risk", "低", 3, "AI 辅助整定校核，保护责任不可替代"),
            R("pr_friendliness", "高", 9, "电气工程紧缺清单"),
            R("pr_difficulty", "低", 4, "紧缺职业，移民相对容易"),
        ],
        "FIT": ["电气/电力背景，愿深耕继电保护与二次系统", "对 IEC 61850、SCADA、保护整定与现场调试感兴趣", "细致严谨，能承担电网安全相关责任", "愿意出差做变电站现场调试并考虑移民"],
        "UNFIT": ["排斥现场调试与变电站出差", "不擅长细致的保护逻辑与规程工作", "电气基础薄弱且无补强意愿"],
        "SOURCES": [
            {"source_name": "Glassdoor", "content": "Protection and Control Engineer AU 约 $110k（$99k~$122k）", "url": "https://www.glassdoor.com/Salaries/melbourne-protection-and-control-engineer-salary-SRCH_IL.0,9_IM965_KO10,41.htm"},
            {"source_name": "Glassdoor AU", "content": "Grid Engineer 澳洲均值约 $133,500", "url": "https://www.glassdoor.com.au/Salaries/grid-engineer-salary-SRCH_KO0,13.htm"},
            {"source_name": "Indeed AU", "content": "Power System Engineer 岗位数百个在招", "url": "https://au.indeed.com/Power-System-Engineer-jobs-in-Australia"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲保护与控制工程师工资多少？", "answer": "初级约 $90k~$115k；中级 $115k~$155k（P&C 工程师约 $110k~$122k 起）；资深继电保护/调试专家 $155k~$195k，含现场津贴。"},
            {"faq_type": "demand", "sort_order": 1, "question": "保护与控制工程师需求大吗？", "answer": "大。可再生并网、储能与换流站建设推动保护与控制需求，资深整定与现场调试工程师尤其稀缺。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外继电保护经验澳洲认可吗？", "answer": "电气学历经 Engineers Australia 评估；IEC 61850、SCADA、保护整定与调试经验是核心加分项，电网与咨询公司乐于录用。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险低。AI 辅助整定校核与故障分析，但保护逻辑设计与电网安全责任由持证工程师承担。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电气工程(233311 家族)紧缺，189/190/482→186 通畅，保护专业经验强化雇主担保。"},
        ],
    },
    # ============================ 6. EV Battery Diagnostics Specialist ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "312412-EVBD", "occ_code_type": "ANZSCO", "anzsco_code": "312412",
                "anzsco_title": "EV Battery Diagnostics Specialist", "category": "Engineering & Infrastructure", "currency": "AUD",
                "workforce_size": 2000, "shortage_listed": 0, "is_migration": 2,
                "growth_areas": json.dumps(["高压电池组诊断与故障定位", "电池健康(SoH)评估与二次利用/梯次利用", "EV 售后与保修诊断(OEM 体系)", "电池维修与模组更换(高压安全)", "储能电池现场诊断与运维"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "电动车电池诊断专家",
               "summary": "电动车电池诊断专家负责高压电池组的故障诊断、健康状态(SoH)评估、模组维修与更换，横跨 EV 售后、保修与储能运维，需要高压安全资质与诊断工具经验。这是随 EV 保有量上升而快速兴起的技术专才岗，介于电子技术员与电工之间。",
               "forecast_note": "澳洲 EV 保有量快速上升带来庞大的电池售后、保修与诊断需求，OEM 与独立维修体系都缺高压诊断人才；但作为技术员级岗位，技术移民路径较受限，多依赖雇主担保。",
               "trend_summary": "2026 年高压电池诊断、SoH 评估与梯次利用成为热点，掌握 OEM 诊断系统与高压安全规程者最抢手。诊断工具与 AI 辅助读取数据，但高压拆装与现场判断仍需人工，AI 替代为部分。"},
        "EN": {"locale": "en", "name": "EV Battery Diagnostics Specialist",
               "summary": "EV battery diagnostics specialists diagnose faults, assess state-of-health (SoH), and repair/replace high-voltage battery modules across EV after-sales, warranty and storage operations — requiring HV safety credentials and diagnostic-tool experience. It is a fast-emerging technical specialist role sitting between electronics technician and electrician as EV fleets grow.",
               "forecast_note": "Australia's rapidly rising EV fleet drives large after-sales, warranty and diagnostics demand; both OEM and independent networks lack HV diagnostics talent. As a technician-level role, skilled-migration pathways are more limited and lean on employer sponsorship.",
               "trend_summary": "In 2026, HV battery diagnostics, SoH assessment and second-life reuse are hotspots; those fluent in OEM diagnostic systems and HV safety procedures are most sought-after. Tools and AI assist data reads, but HV disassembly and on-site judgement stay manual — so AI replacement is partial."},
        "EDU": [
            {"stage": "汽车电气/机电 Certificate III~IV 或电子技术文凭", "duration": "1~2 年", "cost_min": 4000, "cost_max": 20000, "cost_note": "TAFE 或 RTO；EV/高压方向加分", "sort_order": 0},
            {"stage": "高压电动车安全资质（De-energise / HV EV 培训）", "duration": "数天~数周", "cost_min": 500, "cost_max": 3000, "cost_note": "高压电池作业法定安全要求", "sort_order": 1},
            {"stage": "OEM 诊断系统与电池维修培训", "duration": "数周~数月", "cost_min": 1000, "cost_max": 8000, "cost_note": "品牌诊断工具与维修体系", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "高压电动车作业安全资质（HV/De-energise）", "issuer": "认可 RTO / OEM", "note": "高压电池作业法定安全门槛", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "汽车电气/机电 Certificate III~IV", "issuer": "TAFE / RTO", "note": "从业基础资质", "is_mandatory": 1, "sort_order": 1},
            {"qual_name": "OEM 诊断系统认证", "issuer": "各汽车厂商", "note": "售后与保修诊断岗常要求", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 100, "count_max": 350, "note": "EV/电池技术员、诊断、售后岗"},
            {"platform": "Indeed", "count_min": 80, "count_max": 300, "note": "含 EV 技师、电池技术员岗"},
            {"platform": "Jora", "count_min": 100, "count_max": 300, "note": "电池技术员与 EV 维保岗"},
        ],
        "SAL": [
            {"experience": "初级/电池技术员（0~3 年）", "salary_min": 63000, "salary_max": 80000, "salary_note": "电池技术员均值约 $63k，EV 方向更高", "sort_order": 0},
            {"experience": "诊断专家（3~7 年）", "salary_min": 80000, "salary_max": 105000, "salary_note": "EV 电池系统技术员约 $80k~$113k", "sort_order": 1},
            {"experience": "资深/技术主管（8 年+）", "salary_min": 105000, "salary_max": 130000, "salary_note": "资深高压诊断/团队主管", "sort_order": 2},
        ],
        "VISA": VISA_TECH,
        "RATINGS": [
            R("learning_difficulty", "中等", 5, "电气/机电基础 + 高压安全 + 诊断工具"),
            R("learning_duration", "较短", 4, "Cert III~IV + 高压培训约 1~2 年"),
            R("certification_difficulty", "中等", 5, "高压安全资质必需，OEM 认证加分"),
            R("job_demand", "较高", 7, "EV 售后与保修诊断需求上升"),
            R("competition", "中等", 5, "新兴岗，熟手有限但门槛不算极高"),
            R("work_intensity", "中等", 6, "现场诊断与维修，高压作业需谨慎"),
            R("income_level", "中等", 5, "$63k~$113k，资深 $130k"),
            R("future_prospect", "很好", 8, "EV 保有量上升带来长期售后需求"),
            R("ai_risk", "中等", 5, "诊断读数可自动化，高压拆装与判断仍需人"),
            R("pr_friendliness", "中低", 4, "技术员岗，多依赖雇主担保"),
            R("pr_difficulty", "较高", 7, "非工程师岗，独立技术移民难度较大"),
        ],
        "FIT": ["有汽车电气/机电或电子技术员背景，想切入 EV 电池方向", "愿意考取高压电动车作业安全资质并做现场诊断", "对电池健康评估、故障定位与维修有兴趣", "接受以雇主担保为主的移民路径"],
        "UNFIT": ["排斥动手维修与高压作业风险", "希望走独立技术移民的快速通道（此岗受限）", "不愿学习 OEM 诊断系统与安全规程"],
        "SOURCES": [
            {"source_name": "Indeed AU", "content": "Battery Technician 澳洲均值约 $63,124", "url": "https://au.indeed.com/career/battery-technician/salaries"},
            {"source_name": "VisaSponsor Jobs", "content": "Electrical Engineering Technician – EV Battery Systems 约 $80k~$112,882", "url": "https://visasponsor.jobs/api/jobs/a68552cd0eb54c12b13aacb0bb7f971e/Electrical-Engineering-Technician-%E2%80%93-EV-Battery-Systems"},
            {"source_name": "SEEK AU", "content": "Battery Technician 与 EV 技师岗在招", "url": "https://www.seek.com.au/battery-technician-jobs"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲电动车电池诊断专家工资多少？", "answer": "初级/电池技术员约 $63k~$80k；诊断专家 $80k~$105k（EV 电池系统技术员约 $80k~$113k）；资深/主管 $105k~$130k。"},
            {"faq_type": "demand", "sort_order": 1, "question": "这个岗位需求怎样？", "answer": "上行。EV 保有量快速增长带来大量电池售后、保修与诊断需求，OEM 与独立维修体系都缺高压诊断熟手。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外汽车电气/电池经验澳洲认可吗？", "answer": "需取得本地汽车电气/机电资质与高压电动车安全资质；海外 EV 诊断与维修经验有帮助，但高压作业资质是硬门槛。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "部分。诊断读数与故障码分析可自动化，但高压电池拆装、模组更换与现场安全判断仍需人工，属人机协作。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "较难独立移民。作为技术员级岗位路径受限，主要依赖 482 雇主担保或偏远地区提名，建议先在澳就业积累再推进。"},
        ],
    },
    # ============================ 7. Embedded / Firmware Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "261313-EMB", "occ_code_type": "ANZSCO", "anzsco_code": "261313",
                "anzsco_title": "Embedded / Firmware Engineer", "category": "IT & Digital", "currency": "AUD",
                "workforce_size": 12000, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["物联网(IoT)与边缘设备固件", "汽车/医疗/工业嵌入式(功能安全)", "RTOS 与裸机低功耗开发", "无线通信固件(BLE/LoRa/5G 模组)", "嵌入式安全与 OTA 升级"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "嵌入式/固件工程师",
               "summary": "嵌入式/固件工程师在微控制器与 SoC 上开发底层软件，涵盖 RTOS/裸机、驱动、通信协议栈、低功耗与固件安全，广泛应用于物联网、汽车、医疗与工业设备。澳洲在国防、医疗设备、矿业自动化与硬件初创有稳定需求，是软硬件交界的高价值岗位。",
               "forecast_note": "设备联网化与本土硬件/国防制造推动嵌入式需求，SEEK 常年过百个嵌入式固件岗位；软件工程(261313)在技术移民清单，供需稳定偏紧。",
               "trend_summary": "2026 年边缘 AI、汽车与医疗功能安全、设备安全成为热点，懂 C/C++、RTOS 与底层调试的固件工程师稀缺。AI 辅助生成样板代码，但硬件相关的底层调试与实时约束仍高度依赖人。"},
        "EN": {"locale": "en", "name": "Embedded / Firmware Engineer",
               "summary": "Embedded/firmware engineers build low-level software on microcontrollers and SoCs — RTOS/bare-metal, drivers, communication stacks, low-power and firmware security — across IoT, automotive, medical and industrial devices. Australia has steady demand in defence, medical devices, mining automation and hardware startups, making this a high-value hardware-software boundary role.",
               "forecast_note": "Device connectivity plus local hardware/defence manufacturing drive embedded demand; SEEK consistently lists 100+ embedded firmware roles. Software engineering (261313) is on the skilled-migration list, with steady, tight supply-demand.",
               "trend_summary": "In 2026, edge AI, automotive/medical functional safety and device security are hotspots; firmware engineers fluent in C/C++, RTOS and low-level debugging are scarce. AI assists boilerplate generation, but hardware-tied low-level debugging and real-time constraints remain human-heavy."},
        "EDU": [
            {"stage": "计算机/电子/机电工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "嵌入式/RTOS/C++ 与底层调试专项", "duration": "6~18 个月", "cost_min": 1000, "cost_max": 20000, "cost_note": "驱动、通信栈与低功耗实操", "sort_order": 1},
            {"stage": "ACS 技能评估（软件工程 261313）", "duration": "2~4 个月", "cost_min": 500, "cost_max": 1500, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "计算机/电子相关学位", "issuer": "ACS 认可", "note": "移民评估与就业基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "C/C++、RTOS、底层调试能力", "issuer": "项目实践", "note": "固件岗核心竞争力", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "功能安全(ISO 26262/IEC 62304)知识", "issuer": "行业培训", "note": "汽车/医疗方向加分", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 150, "count_max": 500, "note": "嵌入式固件/嵌入式软件岗，约 143+ 常在招"},
            {"platform": "Indeed", "count_min": 100, "count_max": 400, "note": "国防、医疗设备、硬件初创岗"},
            {"platform": "LinkedIn", "count_min": 200, "count_max": 600, "note": "国防承包商与硬件公司直招"},
        ],
        "SAL": [
            {"experience": "初级（0~3 年）", "salary_min": 85000, "salary_max": 110000, "salary_note": "嵌入式软件起薪，均值参考 $90k+", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 110000, "salary_max": 145000, "salary_note": "固件工程 ICT 均值约 $110,929；嵌入式软件约 $118k", "sort_order": 1},
            {"experience": "资深/主任（8 年+）", "salary_min": 145000, "salary_max": 190000, "salary_note": "Senior 约 $128k~$155k，专家更高", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "软硬件交界，C/C++、RTOS 与底层调试难度高"),
            R("learning_duration", "长", 8, "学位 + 数年底层与调试经验"),
            R("certification_difficulty", "低", 4, "无执照，ACS 评估即可"),
            R("job_demand", "高", 8, "设备联网与国防/医疗制造推动"),
            R("competition", "中等", 5, "熟练底层固件人才有限"),
            R("work_intensity", "中等", 6, "调试与发布节点有压力"),
            R("income_level", "较高", 8, "$110k~$145k，资深 $190k"),
            R("future_prospect", "很好", 9, "IoT/边缘 AI/汽车电子长期需求"),
            R("ai_risk", "中低", 4, "AI 生成样板，硬件底层调试与实时约束难替代"),
            R("pr_friendliness", "高", 9, "软件工程 261313 在移民清单"),
            R("pr_difficulty", "低", 4, "紧缺职业，移民相对容易"),
        ],
        "FIT": ["计算机/电子背景，喜欢贴近硬件的底层开发", "熟悉或愿学 C/C++、RTOS、驱动与通信协议栈", "对 IoT、汽车/医疗功能安全或国防电子感兴趣", "希望走软件工程技术移民路径"],
        "UNFIT": ["只想做高层 Web/应用、不愿碰硬件与底层", "缺乏耐心做繁琐的底层调试", "C/C++ 基础薄弱且无补强计划"],
        "SOURCES": [
            {"source_name": "SEEK AU", "content": "固件工程 ICT 均值约 $110,929，约 100+ 岗位；嵌入式固件约 143 岗", "url": "https://www.seek.com.au/career-advice/role/firmware-engineer/salary"},
            {"source_name": "Glassdoor AU", "content": "Embedded Software Engineer 澳洲均值约 $118,750", "url": "https://www.glassdoor.com/Salaries/australia-embedded-software-engineer-salary-SRCH_IL.0,9_IN16_KO10,36.htm"},
            {"source_name": "PayScale AU", "content": "Senior Embedded Software Engineer 约 $128,380（2025）", "url": "https://www.payscale.com/research/AU/Job=Senior_Embedded_Software_Engineer/Salary"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲嵌入式/固件工程师工资多少？", "answer": "初级约 $85k~$110k；中级 $110k~$145k（固件 ICT 均值约 $111k、嵌入式软件约 $118k）；资深 $145k~$190k。"},
            {"faq_type": "demand", "sort_order": 1, "question": "嵌入式工程师在澳洲好找工作吗？", "answer": "较好。设备联网化叠加国防、医疗设备与硬件初创需求，SEEK 常年过百个嵌入式固件岗位，熟练底层人才紧俏。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外学历经验澳洲认可吗？", "answer": "计算机/电子学历经 ACS 评估（软件工程 261313）；C/C++、RTOS、底层调试与功能安全经验是直接加分项。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险中低。AI 生成样板代码与测试，但硬件相关的底层调试、实时约束与安全验证仍高度依赖工程师。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。软件工程(261313)在移民清单，可走 189/190 或 482→186，国防/医疗方向雇主担保意愿强。"},
        ],
    },
    # ============================ 8. FPGA Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233411-FPGA", "occ_code_type": "ANZSCO", "anzsco_code": "233411",
                "anzsco_title": "FPGA Engineer", "category": "IT & Digital", "currency": "AUD",
                "workforce_size": 800, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["国防与航天信号处理(雷达/SDR)", "高频交易(HFT)低延迟 FPGA", "视频/图像与 AI 加速(边缘推理)", "通信基带与 5G/卫星", "FPGA 原型验证与 SoC 加速"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "FPGA 工程师",
               "summary": "FPGA 工程师用 Verilog/VHDL 在可编程逻辑器件上实现高性能数字电路，涵盖信号处理、低延迟计算与硬件加速，主要就业于澳洲国防航天、高频交易与半导体/通信公司。岗位稀缺、门槛高、薪资优厚，是电子工程中的高价值细分。",
               "forecast_note": "澳洲国防(AUKUS/雷达/电子战)、航天与高频交易对 FPGA 需求稳定，岗位数量少但供给更少，资深 FPGA 工程师长期高薪紧俏；电子工程(233411)在技术移民清单。",
               "trend_summary": "2026 年国防信号处理、边缘 AI 加速与低延迟金融计算是主要方向，掌握 Verilog/VHDL、时序收敛与高速接口的工程师稀缺。AI 辅助 RTL 生成有限，硬件时序与验证仍高度专业化。"},
        "EN": {"locale": "en", "name": "FPGA Engineer",
               "summary": "FPGA engineers implement high-performance digital circuits on programmable logic using Verilog/VHDL — spanning signal processing, low-latency compute and hardware acceleration — mainly in Australian defence/aerospace, high-frequency trading and semiconductor/telecom firms. Roles are scarce, demanding and well-paid, a high-value electronics-engineering niche.",
               "forecast_note": "Australian defence (AUKUS/radar/EW), aerospace and HFT sustain FPGA demand; role counts are small but supply is smaller, keeping senior FPGA engineers well-paid and scarce. Electronics engineering (233411) is on the skilled-migration list.",
               "trend_summary": "In 2026, defence signal processing, edge-AI acceleration and low-latency finance dominate; engineers strong in Verilog/VHDL, timing closure and high-speed interfaces are scarce. AI's help with RTL is limited, and hardware timing/verification stay highly specialised."},
        "EDU": [
            {"stage": "电子/电气/计算机工程学士（4 年）", "duration": "4 年", "cost_min": 40000, "cost_max": 160000, "cost_note": "本地生 CSP 约 $40k；国际生约 $140k~$160k", "sort_order": 0},
            {"stage": "数字设计/FPGA 专项（Verilog/VHDL、时序收敛、高速接口）", "duration": "6~24 个月", "cost_min": 2000, "cost_max": 40000, "cost_note": "RTL、时序与验证实操核心", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估（电子工程）", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须；国防岗常需公民/安全许可", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电子/电气/计算机工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "Verilog/VHDL、时序收敛与验证能力", "issuer": "项目实践", "note": "FPGA 岗核心竞争力", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "安全许可(Security Clearance)", "issuer": "澳洲政府", "note": "国防航天岗常要求，需公民身份", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 9, "count_max": 60, "note": "FPGA/数字设计岗，数量少但高价值"},
            {"platform": "Glassdoor", "count_min": 20, "count_max": 60, "note": "约 27 个 FPGA 工程师岗"},
            {"platform": "LinkedIn", "count_min": 30, "count_max": 120, "note": "国防/航天/半导体/HFT 直招"},
        ],
        "SAL": [
            {"experience": "初级（1~3 年）", "salary_min": 110000, "salary_max": 140000, "salary_note": "入门 FPGA 均值约 $114,162", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 140000, "salary_max": 175000, "salary_note": "Indeed 均值约 $145,936；悉尼约 $140k", "sort_order": 1},
            {"experience": "资深（8 年+）", "salary_min": 175000, "salary_max": 210000, "salary_note": "SalaryExpert 均值约 $162k；资深约 $201,853", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "很高", 9, "RTL、时序收敛与高速接口高度专业"),
            R("learning_duration", "长", 8, "学位 + 数年数字设计与验证经验"),
            R("certification_difficulty", "低", 4, "无执照；国防岗需安全许可"),
            R("job_demand", "中等", 6, "岗位少但供给更少，结构性紧缺"),
            R("competition", "低", 4, "熟练 FPGA 工程师稀缺"),
            R("work_intensity", "中等", 6, "时序收敛与流片/交付节点压力"),
            R("income_level", "高", 9, "$140k~$175k，资深 $200k+"),
            R("future_prospect", "很好", 8, "国防/边缘 AI/低延迟金融长期需求"),
            R("ai_risk", "低", 3, "AI 辅助 RTL 有限，硬件时序/验证难替代"),
            R("pr_friendliness", "较高", 8, "电子工程 233411 在移民清单"),
            R("pr_difficulty", "中低", 5, "岗位少，需锁定雇主，但职业紧缺"),
        ],
        "FIT": ["电子/计算机工程背景，热爱数字硬件设计", "掌握或愿深耕 Verilog/VHDL、时序收敛与高速接口", "对国防航天、HFT 或边缘 AI 加速方向感兴趣", "接受岗位数量少但高薪、需锁定雇主的现实"],
        "UNFIT": ["偏好软件应用、不愿钻研硬件时序", "需要大量岗位选择与快速跳槽（此岗小众）", "国防岗但不满足公民/安全许可要求且只盯国防"],
        "SOURCES": [
            {"source_name": "Indeed AU", "content": "FPGA Engineer 均值约 $145,936；悉尼约 $140k", "url": "https://au.indeed.com/career/fpga-engineer/salaries"},
            {"source_name": "ERI SalaryExpert", "content": "均值约 $162,372；入门约 $114k，资深约 $201,853", "url": "https://www.salaryexpert.com/salary/job/fpga-engineer/australia"},
            {"source_name": "Glassdoor AU", "content": "澳洲约 27 个 FPGA 工程师岗（2025）", "url": "https://www.glassdoor.com.au/Job/australia-fpga-engineer-jobs-SRCH_IL.0,9_IN16_KO10,23.htm"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲 FPGA 工程师工资多少？", "answer": "入门约 $110k~$140k（均值约 $114k）；中级 $140k~$175k（Indeed 约 $146k）；资深 $175k~$210k（可达 $201,853）。属高薪电子细分。"},
            {"faq_type": "demand", "sort_order": 1, "question": "FPGA 工程师在澳洲好找工作吗？", "answer": "岗位数量少（SEEK 约 9、Glassdoor 约 27），但供给更少，属结构性紧缺。集中在国防航天、HFT 与半导体/通信公司，往往需锁定特定雇主。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外 FPGA 经验澳洲认可吗？", "answer": "电子工程学历经 Engineers Australia 评估；Verilog/VHDL、时序收敛与验证经验高度受认可。注意国防岗常要求公民身份与安全许可。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险低。AI 对 RTL 生成帮助有限，硬件时序收敛、验证与系统集成高度专业，短期难以替代。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电子工程(233411)在移民清单，可走 189/190 或 482→186；因岗位少，雇主担保常是更现实的通道。"},
        ],
    },
    # ============================ 9. ASIC Design Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233411-ASIC", "occ_code_type": "ANZSCO", "anzsco_code": "233411",
                "anzsco_title": "ASIC Design Engineer", "category": "IT & Digital", "currency": "AUD",
                "workforce_size": 400, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["数字前端 RTL 设计与综合", "低功耗/高性能 SoC 设计", "AI 加速器与专用芯片(ASIC)", "后端物理设计与时序收敛", "芯片初创与无晶圆(fabless)设计"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "ASIC 芯片设计工程师",
               "summary": "ASIC 设计工程师负责专用集成电路的数字前端(RTL 设计/综合)或后端(物理设计/时序收敛)，面向 SoC、AI 加速器与专用芯片。澳洲半导体设计规模不大但在快速兴起（芯片初创、国防与研究机构），是稀缺、高门槛、高薪的深科技岗位。",
               "forecast_note": "全球芯片自主与 AI 加速需求外溢，澳洲 fabless 设计与芯片初创增多，ERI 预计该岗薪资 5 年上涨约 15%；岗位稀缺、资深设计人才极度紧缺，电子工程(233411)在移民清单。",
               "trend_summary": "2026 年 AI 加速器与低功耗 SoC 是主线，掌握 RTL、综合、时序与后端流程的设计工程师稀缺。AI 辅助部分 RTL 与验证，但架构、时序收敛与流片责任高度专业。"},
        "EN": {"locale": "en", "name": "ASIC Design Engineer",
               "summary": "ASIC design engineers handle the digital front-end (RTL design/synthesis) or back-end (physical design/timing closure) of application-specific chips for SoCs, AI accelerators and specialised silicon. Australia's chip-design base is small but rising fast (chip startups, defence and research), making this a scarce, high-barrier, high-pay deep-tech role.",
               "forecast_note": "Global chip-sovereignty and AI-acceleration demand spill over; Australia's fabless design and chip startups are growing. ERI projects ~15% salary growth over five years; roles are scarce and senior design talent is in severe shortage. Electronics engineering (233411) is on the skilled-migration list.",
               "trend_summary": "In 2026, AI accelerators and low-power SoCs lead; engineers fluent in RTL, synthesis, timing and back-end flows are scarce. AI assists some RTL and verification, but architecture, timing closure and tape-out accountability stay highly specialised."},
        "EDU": [
            {"stage": "电子/微电子/计算机工程学士（4 年），常需硕士", "duration": "4~6 年", "cost_min": 40000, "cost_max": 200000, "cost_note": "微电子/VLSI 硕士方向竞争力更强", "sort_order": 0},
            {"stage": "VLSI/数字设计专项（RTL、综合、时序、后端流程）", "duration": "1~2 年", "cost_min": 3000, "cost_max": 40000, "cost_note": "EDA 工具链与流片流程实操", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估（电子工程）", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电子/微电子/计算机工程学位（常需硕士）", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "RTL/综合/时序/后端与 EDA 工具能力", "issuer": "项目实践", "note": "ASIC 设计核心竞争力", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "流片(tape-out)项目经验", "issuer": "行业", "note": "资深岗高度看重", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 5, "count_max": 40, "note": "ASIC/IC 设计岗，数量少高价值"},
            {"platform": "Indeed", "count_min": 5, "count_max": 40, "note": "含芯片初创、国防与研究机构"},
            {"platform": "LinkedIn", "count_min": 15, "count_max": 60, "note": "fabless 设计公司与初创直招"},
        ],
        "SAL": [
            {"experience": "初级（1~3 年）", "salary_min": 105000, "salary_max": 135000, "salary_note": "入门约 $104,001", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 135000, "salary_max": 170000, "salary_note": "均值约 $148,133（含奖金）", "sort_order": 1},
            {"experience": "资深（8 年+）", "salary_min": 170000, "salary_max": 210000, "salary_note": "资深约 $168,808，墨尔本略高", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "很高", 9, "VLSI、EDA 流程与流片高度复杂"),
            R("learning_duration", "很长", 9, "学位常需硕士 + 多年设计与流片经验"),
            R("certification_difficulty", "低", 4, "无执照，ACS/EA 评估即可"),
            R("job_demand", "中等偏低", 5, "澳洲岗位稀缺但供给更少"),
            R("competition", "低", 4, "资深设计人才极稀缺"),
            R("work_intensity", "较高", 7, "流片节点与时序收敛压力大"),
            R("income_level", "高", 9, "$135k~$170k，资深 $210k"),
            R("future_prospect", "很好", 8, "AI 芯片与芯片自主长期利好，+15%/5 年"),
            R("ai_risk", "低", 3, "AI 辅助有限，架构/时序/流片责任难替代"),
            R("pr_friendliness", "较高", 8, "电子工程 233411 在移民清单"),
            R("pr_difficulty", "中低", 5, "岗位少，需锁定雇主，但职业紧缺"),
        ],
        "FIT": ["微电子/电子背景，愿深耕芯片设计深科技", "掌握或愿学 RTL、综合、时序收敛与后端流程", "对 AI 加速器、低功耗 SoC 与流片有热情", "接受澳洲岗位稀少但高薪、需锁定雇主的现实"],
        "UNFIT": ["希望大量岗位与快速跳槽（澳洲极小众）", "不愿投入长期高强度学习（常需硕士）", "排斥流片节点的高压交付"],
        "SOURCES": [
            {"source_name": "ERI SalaryExpert", "content": "ASIC Design Engineer 均值约 $148,133；入门约 $104k、资深约 $168,808；5 年 +15%", "url": "https://www.salaryexpert.com/salary/job/asic-design-engineer/australia"},
            {"source_name": "Glassdoor", "content": "ASIC Design Engineer 薪资趋势（2026）", "url": "https://www.glassdoor.com/Salaries/asic-design-engineer-salary-SRCH_KO0,20.htm"},
            {"source_name": "PayScale AU", "content": "半导体工程设计技能薪资参考", "url": "https://www.payscale.com/research/AU/Skill=Engineering_Design%2C_Semiconductor/Salary"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲 ASIC 芯片设计工程师工资多少？", "answer": "入门约 $105k~$135k（约 $104k）；中级 $135k~$170k（均值约 $148k 含奖金）；资深 $170k~$210k（约 $168,808）。ERI 预计 5 年上涨约 15%。"},
            {"faq_type": "demand", "sort_order": 1, "question": "ASIC 设计工程师在澳洲好找工作吗？", "answer": "岗位稀缺（SEEK/Indeed 常仅个位到数十个），但资深设计人才供给更少，属结构性紧缺，集中在芯片初创、国防与研究机构，通常需锁定特定雇主。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外芯片设计经验澳洲认可吗？", "answer": "电子/微电子学历经 Engineers Australia 评估；RTL、综合、时序收敛与流片经验高度受认可，fabless 公司乐于招募有实战流片经验者。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险低。AI 辅助部分 RTL 与验证，但架构设计、时序收敛与流片责任高度专业，短期难以替代。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电子工程(233411)在移民清单，可走 189/190 或 482→186；因岗位少，雇主担保常更现实。"},
        ],
    },
    # ============================ 10. Analog / Mixed-Signal IC Design Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233411-AMS", "occ_code_type": "ANZSCO", "anzsco_code": "233411",
                "anzsco_title": "Analog / Mixed-Signal IC Design Engineer", "category": "IT & Digital", "currency": "AUD",
                "workforce_size": 300, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["数据转换器(ADC/DAC)与 PLL/时钟", "电源管理 IC(PMIC)与 LDO", "射频/无线前端(RFIC)", "传感器接口与信号链", "SerDes 与高速模拟接口"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "模拟/混合信号 IC 设计工程师",
               "summary": "模拟/混合信号 IC 设计工程师设计芯片中的模拟与数模混合模块，如 ADC/DAC、PLL、电源管理(PMIC)、射频前端与高速接口，是公认最难自动化、最依赖经验直觉的芯片设计方向。澳洲此类专家极为稀缺，薪资位于电子工程顶端。",
               "forecast_note": "模拟设计经验壁垒极高、全球性稀缺，澳洲相关岗位虽少但供给更少，资深模拟工程师长期高薪难招；电子工程(233411)在技术移民清单。",
               "trend_summary": "2026 年电源管理、传感器信号链与射频前端需求旺盛，掌握晶体管级设计、版图与工艺理解的模拟工程师最稀缺。AI 对模拟设计帮助最小，经验直觉与手工优化不可替代。"},
        "EN": {"locale": "en", "name": "Analog / Mixed-Signal IC Design Engineer",
               "summary": "Analog/mixed-signal IC design engineers design the analog and mixed-signal blocks in chips — ADC/DAC, PLLs, power management (PMIC), RF front-ends and high-speed interfaces — widely regarded as the hardest to automate and most experience-driven area of chip design. Such experts are extremely scarce in Australia, with pay at the top of electronics engineering.",
               "forecast_note": "Analog design carries a very high experience barrier and is globally scarce; Australian roles are few but supply is fewer, so senior analog engineers stay well-paid and hard to hire. Electronics engineering (233411) is on the skilled-migration list.",
               "trend_summary": "In 2026, power management, sensor signal chains and RF front-ends are in strong demand; analog engineers fluent in transistor-level design, layout and process understanding are the scarcest. AI helps analog design least — experience-driven intuition and hand optimisation remain irreplaceable."},
        "EDU": [
            {"stage": "电子/微电子工程学士 + 硕士/博士（模拟方向）", "duration": "5~8 年", "cost_min": 40000, "cost_max": 220000, "cost_note": "模拟设计常需研究型学位与深厚基础", "sort_order": 0},
            {"stage": "模拟/混合信号专项（晶体管级设计、版图、工艺）", "duration": "2~3 年", "cost_min": 3000, "cost_max": 40000, "cost_note": "经验壁垒高，需长期实战", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估（电子工程）", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电子/微电子工程学位（常需硕/博）", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "晶体管级模拟设计与版图能力", "issuer": "项目实践", "note": "模拟岗核心且稀缺", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "流片(tape-out)与硅验证经验", "issuer": "行业", "note": "资深岗高度看重", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 3, "count_max": 30, "note": "模拟/混合信号 IC 设计岗，极少高价值"},
            {"platform": "Glassdoor", "count_min": 10, "count_max": 40, "note": "约 15 个 IC 设计岗（含模拟）"},
            {"platform": "LinkedIn", "count_min": 10, "count_max": 50, "note": "半导体公司与初创直招，猎头活跃"},
        ],
        "SAL": [
            {"experience": "初级（1~3 年）", "salary_min": 100000, "salary_max": 130000, "salary_note": "半导体设计澳洲基准约 $110k~$118k", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 130000, "salary_max": 170000, "salary_note": "模拟溢价高于数字，参考 IC 设计区间", "sort_order": 1},
            {"experience": "资深（8 年+）", "salary_min": 170000, "salary_max": 215000, "salary_note": "资深模拟专家位于电子工程薪资顶端", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "极高", 10, "晶体管级模拟设计经验壁垒最高"),
            R("learning_duration", "很长", 9, "常需硕/博 + 多年实战积累"),
            R("certification_difficulty", "低", 4, "无执照，EA/ACS 评估即可"),
            R("job_demand", "中等偏低", 5, "澳洲岗位极少但供给更少"),
            R("competition", "极低", 3, "资深模拟专家全球性稀缺"),
            R("work_intensity", "较高", 7, "流片与硅验证节点压力大"),
            R("income_level", "高", 9, "$130k~$170k，资深 $215k"),
            R("future_prospect", "很好", 8, "电源/射频/传感长期需求"),
            R("ai_risk", "极低", 2, "模拟设计最难自动化，经验直觉不可替代"),
            R("pr_friendliness", "较高", 8, "电子工程 233411 在移民清单"),
            R("pr_difficulty", "中低", 5, "岗位少需锁定雇主，但职业极紧缺"),
        ],
        "FIT": ["微电子/电子背景，愿长期钻研模拟这一硬核方向", "对 ADC/DAC、PLL、PMIC、RFIC 或信号链有热情", "享受晶体管级设计与手工优化的深度工作", "接受岗位极少但薪资顶端、需锁定雇主的现实"],
        "UNFIT": ["希望快速见效或大量岗位选择", "不愿投入研究型学位与多年积累", "偏好数字/软件、对模拟直觉不感兴趣"],
        "SOURCES": [
            {"source_name": "PayScale AU", "content": "半导体工程设计技能澳洲基准约 $110k~$118k", "url": "https://www.payscale.com/research/AU/Skill=Engineering_Design%2C_Semiconductor/Salary"},
            {"source_name": "Glassdoor AU", "content": "澳洲约 15 个 IC 设计工程师岗（含模拟/混合信号）", "url": "https://www.glassdoor.com/Job/australia-ic-design-engineer-jobs-SRCH_IL.0,9_IN16_KO10,28.htm"},
            {"source_name": "Levels.fyi", "content": "模拟/混合信号硬件工程师全球薪资参考（模拟溢价明显）", "url": "https://www.levels.fyi/t/hardware-engineer/focus/analog"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲模拟/混合信号 IC 设计工程师工资多少？", "answer": "初级约 $100k~$130k；中级 $130k~$170k；资深模拟专家 $170k~$215k，位于电子工程薪资顶端。模拟经验稀缺使溢价高于数字设计。"},
            {"faq_type": "demand", "sort_order": 1, "question": "这个岗位在澳洲好找工作吗？", "answer": "岗位极少（常仅个位数），但资深模拟专家全球性稀缺、供给更少，一旦匹配非常抢手，通常需锁定特定半导体公司或初创。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外模拟设计经验澳洲认可吗？", "answer": "电子/微电子学历经 Engineers Australia 评估；晶体管级设计、版图与流片经验高度受认可，是稀缺硬通货。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险极低。模拟设计公认最难自动化，依赖工程师的经验直觉、手工优化与工艺理解，AI 短期帮助有限。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电子工程(233411)在移民清单，可走 189/190 或 482→186；因岗位极少，雇主担保常是现实通道，但职业极度紧缺利于谈判。"},
        ],
    },
    # ============================ 11. IC Verification Engineer ============================
    {
        "OCC": {"country_code": "AU", "occ_code": "233411-ICV", "occ_code_type": "ANZSCO", "anzsco_code": "233411",
                "anzsco_title": "IC Verification Engineer", "category": "IT & Digital", "currency": "AUD",
                "workforce_size": 600, "shortage_listed": 1, "is_migration": 1,
                "growth_areas": json.dumps(["UVM/SystemVerilog 功能验证", "覆盖率驱动与形式化验证", "SoC 级验证与仿真环境", "低功耗/安全验证(UPF、ISO 26262)", "验证方法学与自动化(含 AI 辅助)"], ensure_ascii=False)},
        "ZH": {"locale": "zh-CN", "name": "IC 验证工程师",
               "summary": "IC 验证工程师在芯片流片前用 SystemVerilog/UVM 搭建验证环境、编写测试平台、做覆盖率驱动与形式化验证，确保设计符合规格。验证工作量通常占芯片开发一半以上，岗位比设计更多，是进入半导体行业相对可行的高薪路径。",
               "forecast_note": "芯片复杂度上升使验证需求增长，验证岗通常多于设计岗；澳洲半导体设计兴起带动验证招聘，电子工程(233411)在技术移民清单，掌握 UVM 与覆盖率方法学者紧俏。",
               "trend_summary": "2026 年 SoC 级验证、低功耗与安全验证、以及 AI 辅助验证成为重点。AI 提升测试生成与调试效率，但验证方法学、覆盖率收敛与规格理解仍由工程师主导。"},
        "EN": {"locale": "en", "name": "IC Verification Engineer",
               "summary": "IC verification engineers build verification environments and testbenches in SystemVerilog/UVM and run coverage-driven and formal verification before tape-out, ensuring designs meet spec. Verification typically takes over half of chip-development effort, and roles outnumber design roles — a relatively feasible high-paid route into semiconductors.",
               "forecast_note": "Rising chip complexity grows verification demand, and verification roles usually outnumber design roles. Australia's emerging chip-design base lifts verification hiring; electronics engineering (233411) is on the skilled-migration list, with UVM/coverage-methodology experts in demand.",
               "trend_summary": "In 2026, SoC-level verification, low-power/safety verification and AI-assisted verification are focal points. AI boosts test generation and debug efficiency, but verification methodology, coverage closure and spec understanding stay engineer-led."},
        "EDU": [
            {"stage": "电子/计算机/微电子工程学士（4 年），硕士加分", "duration": "4~6 年", "cost_min": 40000, "cost_max": 200000, "cost_note": "VLSI/验证方向硕士更具竞争力", "sort_order": 0},
            {"stage": "验证专项（SystemVerilog、UVM、覆盖率、形式化）", "duration": "6~18 个月", "cost_min": 2000, "cost_max": 30000, "cost_note": "UVM 方法学与仿真工具实操核心", "sort_order": 1},
            {"stage": "Engineers Australia 职业评估（电子工程）", "duration": "3~6 个月", "cost_min": 600, "cost_max": 3000, "cost_note": "技术移民必须", "sort_order": 2},
        ],
        "QUAL": [
            {"qual_name": "认可电子/计算机工程学位", "issuer": "Engineers Australia", "note": "执业与移民评估基础", "is_mandatory": 1, "sort_order": 0},
            {"qual_name": "SystemVerilog/UVM 与覆盖率驱动验证能力", "issuer": "项目实践", "note": "验证岗核心竞争力", "is_mandatory": 0, "sort_order": 1},
            {"qual_name": "形式化验证/低功耗/安全验证经验", "issuer": "行业", "note": "资深岗加分", "is_mandatory": 0, "sort_order": 2},
        ],
        "JOBS": [
            {"platform": "Seek", "count_min": 5, "count_max": 40, "note": "验证/DV 工程师岗，通常多于设计岗"},
            {"platform": "Glassdoor", "count_min": 15, "count_max": 50, "note": "半导体验证岗（含 SoC/ASIC 验证）"},
            {"platform": "LinkedIn", "count_min": 20, "count_max": 70, "note": "半导体公司与初创直招"},
        ],
        "SAL": [
            {"experience": "初级（1~3 年）", "salary_min": 100000, "salary_max": 125000, "salary_note": "半导体设计澳洲基准约 $110k", "sort_order": 0},
            {"experience": "中级（3~7 年）", "salary_min": 125000, "salary_max": 160000, "salary_note": "验证经验上升，接近设计岗薪资", "sort_order": 1},
            {"experience": "资深（8 年+）", "salary_min": 160000, "salary_max": 200000, "salary_note": "资深验证/方法学专家", "sort_order": 2},
        ],
        "VISA": VISA_ENG,
        "RATINGS": [
            R("learning_difficulty", "高", 8, "SystemVerilog/UVM 与验证方法学要求高"),
            R("learning_duration", "长", 8, "学位 + 数年验证方法学与项目经验"),
            R("certification_difficulty", "低", 4, "无执照，EA/ACS 评估即可"),
            R("job_demand", "中等", 6, "验证岗多于设计岗，随芯片复杂度上升"),
            R("competition", "低", 4, "UVM 熟手在澳有限"),
            R("work_intensity", "较高", 7, "覆盖率收敛与流片节点压力"),
            R("income_level", "较高", 8, "$125k~$160k，资深 $200k"),
            R("future_prospect", "很好", 8, "芯片复杂度上升长期利好"),
            R("ai_risk", "低", 3, "AI 提升效率，但方法学与覆盖率收敛主导在人"),
            R("pr_friendliness", "较高", 8, "电子工程 233411 在移民清单"),
            R("pr_difficulty", "中低", 5, "岗位有限需锁定雇主，但职业紧缺"),
        ],
        "FIT": ["电子/计算机背景，想进半导体但设计岗太窄", "掌握或愿学 SystemVerilog、UVM 与覆盖率驱动验证", "细致、擅长找边界条件与系统性测试", "看重验证岗数量多于设计岗、相对可行的入行路径"],
        "UNFIT": ["缺乏耐心做系统性测试与调试", "只想做设计不愿做验证", "SystemVerilog/方法学基础薄弱且无补强计划"],
        "SOURCES": [
            {"source_name": "PayScale AU", "content": "半导体设计工程澳洲基准约 $110k", "url": "https://www.payscale.com/research/AU/Skill=Engineering_Design%2C_Semiconductor/Salary"},
            {"source_name": "Glassdoor AU", "content": "Design Verification Engineer 澳洲薪资参考", "url": "https://glassdoor.com/Salaries/australia-design-verification-engineer-salary-SRCH_IL.0,9_IN16_KO10,38.htm"},
            {"source_name": "IC Resources", "content": "IC 验证(UVM/SystemVerilog)岗位方法学与需求说明", "url": "https://ic-resources.com/en/sector/ic-verification/"},
        ],
        "FAQS": [
            {"faq_type": "salary", "sort_order": 0, "question": "澳洲 IC 验证工程师工资多少？", "answer": "初级约 $100k~$125k；中级 $125k~$160k；资深方法学专家 $160k~$200k。验证岗薪资接近设计岗，且岗位数量更多。"},
            {"faq_type": "demand", "sort_order": 1, "question": "IC 验证工程师在澳洲好找工作吗？", "answer": "相对可行。验证工作量占芯片开发一半以上，验证岗通常多于设计岗；澳洲半导体设计兴起带动验证招聘，UVM 熟手紧俏。"},
            {"faq_type": "recognition", "sort_order": 2, "question": "海外验证经验澳洲认可吗？", "answer": "电子/计算机学历经 Engineers Australia 评估；SystemVerilog、UVM、覆盖率与形式化验证经验高度受认可。"},
            {"faq_type": "ai_risk", "sort_order": 3, "question": "会被 AI 替代吗？", "answer": "风险低。AI 提升测试生成与调试效率，但验证方法学设计、覆盖率收敛与规格理解仍由工程师主导，属增强型岗位。"},
            {"faq_type": "difficulty", "sort_order": 4, "question": "能技术移民吗？", "answer": "能。电子工程(233411)在移民清单，可走 189/190 或 482→186；验证岗数量多于设计岗，是进入半导体并移民相对可行的路径。"},
        ],
    },
]


def run():
    with get_cursor() as cur:
        for r in ROLES:
            oid = seed_occupation_v2(
                cur, r["OCC"], r["ZH"], r["EN"], r["EDU"], r["QUAL"], r["JOBS"],
                r["SAL"], r["VISA"], r["RATINGS"], r["FIT"], r["UNFIT"], r["SOURCES"], r["FAQS"])
            print(f"  -> {r['OCC']['anzsco_title']} (id={oid})")
    print(f"\n[OK] 已入库 {len(ROLES)} 个 AU 能源/半导体新兴职业")


if __name__ == "__main__":
    run()
