"""批量入库 27 个职业（2026-06）+ 生成 markdown。
含 is_migration 标识；薪资为联网检索（Seek/JSA/Glassdoor 2025-2026）区间估算。
可重复运行（seed_occupation_v2 幂等）。"""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.dirname(__file__))
from db.connection import get_cursor
from _seed_helper import seed_occupation_v2
from pipeline.generators.md_generator import generate_md

DIMS = ["learning_difficulty", "learning_duration", "certification_difficulty",
        "job_demand", "competition", "work_intensity", "income_level",
        "future_prospect", "ai_risk", "pr_friendliness", "pr_difficulty"]


def R(d):  # d: {dim: (label_zh, stars)}
    return [{"dimension": k, "label_zh": v[0], "stars": v[1]} for k, v in d.items()]


def EDU(rows):
    return [{"stage": s, "duration": dur, "cost_min": a, "cost_max": b, "cost_note": n, "sort_order": i}
            for i, (s, dur, a, b, n) in enumerate(rows)]


def QUAL(rows):
    return [{"qual_name": q, "issuer": iss, "note": nt, "is_mandatory": m, "sort_order": i}
            for i, (q, iss, nt, m) in enumerate(rows)]


def LIST(rows):
    return [{"platform": p, "count_min": a, "count_max": b, "note": n} for (p, a, b, n) in rows]


def SAL(rows):
    return [{"experience": e, "salary_min": a, "salary_max": b, "salary_note": n, "sort_order": i}
            for i, (e, a, b, n) in enumerate(rows)]


def VISA(rows):
    return [{"visa_subclass": s, "visa_name": nm, "description": d, "sort_order": i}
            for i, (s, nm, d) in enumerate(rows)]


def FAQ(rows):
    return [{"faq_type": t, "sort_order": i, "question": q, "answer": a} for i, (t, q, a) in enumerate(rows)]


# 非移民职业通用签证空 + 低 PR 评分；移民职业通用三签证
VISA_MIG = VISA([
    ("482", "Skills in Demand", "雇主担保（旧称TSS），按具体职责匹配ANZSCO"),
    ("186", "ENS", "雇主担保永居，需相关评估"),
    ("190", "Skilled Nominated", "州提名，按各州清单"),
])

SRC_JSA = ("JSA / JobOutlook", "ANZSCO 就业、人数与需求", "https://www.jobsandskills.gov.au/")
SRC_SEEK = ("Seek AU", "薪资与岗位量参考", "https://www.seek.com.au/")

# ───────────────────────── 27 个职业数据 ─────────────────────────
OCCS = [
 # ---- 商业/管理/文职（多为非移民） ----
 dict(code="142111", en="Retail Manager (General)", zh="零售经理", cat="Hospitality, Retail & Tourism",
      mig=1, short=0, wf=230000, growth=["Omnichannel Retail", "Franchise Management", "Loss Prevention", "Customer Experience"],
      sum_zh="零售经理负责门店运营、库存、排班和团队管理，对接销售目标与顾客体验。部分州清单可技术移民（需VETASSESS评估）。",
      sum_en="Retail managers run store operations, stock, rostering and teams against sales targets; available on some state skilled lists via VETASSESS.",
      fc="零售管理需求稳定，连锁化与全渠道运营推动对有数据和团队管理能力者的需求。", tr="晋升路径：主管→店长→区域经理；具备P&L和库存系统经验者更抢手。",
      edu=[("无强制学历（经验导向）", "—", 0, 0, "多由资深销售晋升"), ("Diploma of Retail/Business Management（可选）", "1~2年", 5000, 18000, "利于晋升")],
      qual=[("Diploma of Leadership and Management（可选）", "TAFE/RTO", "非强制", 0), ("VETASSESS Skills Assessment（移民用）", "VETASSESS", "技术移民评估", 0)],
      listings=[("Seek", 4000, 7000, "全国"), ("Indeed", 2500, 4500, "全国")],
      sal=[("初级店长", 60000, 75000, "小型门店"), ("中级（3-8年）", 75000, 95000, "中大型门店"), ("区域/资深", 95000, 130000, "多店/区域")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["有零售一线经验想带团队者", "擅长运营与数字管理的人", "想走州担保移民的零售从业者"],
      unfit=["不愿处理周末与排班压力者", "排斥销售目标考核的人"],
      faqs=[("salary", "澳洲零售经理工资多少？", "店长约AUD $6万~$9.5万，区域或资深经理可达$13万。规模与所在州差异较大。"),
            ("migration", "零售经理能技术移民吗？", "可以但有限。Retail Manager（142111）在部分州提名清单上，需VETASSESS技能评估，189独立技术移民一般不适用。")]),
 dict(code="532111", en="General Clerk", zh="普通文员", cat="Business, Finance & Legal",
      mig=0, short=0, wf=180000, growth=["Office Automation", "Data Entry & CRM", "Records Digitisation"],
      sum_zh="普通文员处理文件录入、归档、收发与日常行政事务，是各类机构的基础支持岗位，门槛低、入职快，非技术移民职业。",
      sum_en="General clerks handle data entry, filing and routine administration; an accessible entry-level support role, not a skilled migration occupation.",
      fc="基础文职受办公自动化与AI挤压，但行政支持需求长期存在，向行政协调/办公室管理发展空间较好。", tr="可向行政主管、办公室经理路径发展；熟练Excel与CRM系统更有竞争力。",
      edu=[("高中/Certificate II-III in Business（可选）", "0~1年", 0, 4000, "在岗培训为主")],
      qual=[("Certificate III in Business (BSB30120)", "TAFE/RTO", "非强制", 0)],
      listings=[("Seek", 3000, 6000, "全国"), ("Indeed", 2500, 5000, "全国")],
      sal=[("入门（0-2年）", 50000, 58000, "全职"), ("有经验（2-5年）", 58000, 70000, "—"), ("资深/行政协调", 70000, 80000, "—")],
      visa=[],
      rat={"learning_difficulty": ("很低", 1), "learning_duration": ("很短", 1), "certification_difficulty": ("很低", 1),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("较低", 2), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细心、擅长文档与流程的人", "想进入办公室行政路径的新人"],
      unfit=["以技术移民为目标者", "追求高薪或快速晋升者"],
      faqs=[("salary", "澳洲普通文员工资多少？", "约AUD $5万~$8万，资深行政协调可到$8万。"),
            ("migration", "普通文员能技术移民吗？", "不能，属于非技术移民职业，不在技术移民清单上。")]),
 dict(code="542111", en="Receptionist", zh="前台", cat="Business, Finance & Legal",
      mig=0, short=0, wf=150000, growth=["Front Office Tech", "Customer Service", "Virtual Reception"],
      sum_zh="前台负责接待来访、接听电话、预约安排和基础行政，是企业门面岗位，门槛低，非技术移民职业。",
      sum_en="Receptionists greet visitors, answer calls, manage bookings and basic admin; a front-of-house entry role, not a skilled migration occupation.",
      fc="前台需求稳定但部分被虚拟前台/自助系统替代，服务与协调能力强者更稳。", tr="可向行政、办公室管理或客户服务方向发展。",
      edu=[("高中 / Certificate in Business（可选）", "0~1年", 0, 3500, "在岗培训")],
      qual=[("Certificate III in Business (BSB30120)", "TAFE/RTO", "非强制", 0)],
      listings=[("Seek", 3500, 6500, "全国"), ("Indeed", 2500, 4500, "全国")],
      sal=[("入门", 50000, 58000, "全职"), ("有经验", 58000, 68000, "—"), ("资深前台/行政", 68000, 75000, "—")],
      visa=[],
      rat={"learning_difficulty": ("很低", 1), "learning_duration": ("很短", 1), "certification_difficulty": ("很低", 1),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["亲和、沟通能力强的人", "想进入行政/客户服务的新人"],
      unfit=["以技术移民为目标者", "不擅长多任务与人际沟通者"],
      faqs=[("salary", "澳洲前台工资多少？", "约AUD $5万~$7.5万。"),
            ("migration", "前台能技术移民吗？", "不能，非技术移民职业。")]),
 dict(code="542114", en="Medical Receptionist", zh="医疗前台", cat="Healthcare & Care",
      mig=0, short=0, wf=60000, growth=["Practice Software (Best Practice/MD)", "Telehealth Admin", "Patient Coordination"],
      sum_zh="医疗前台在诊所、医院和专科为患者预约、登记、结算并管理病历系统（如Best Practice/Medical Director），需熟悉Medicare流程，非技术移民职业。",
      sum_en="Medical receptionists manage bookings, registration, billing and clinical software in clinics and hospitals; not a skilled migration occupation.",
      fc="人口老龄化与医疗扩张支撑稳定需求，熟悉Medicare与诊所软件者更抢手。", tr="可向诊所行政、Practice Manager方向发展。",
      edu=[("Certificate III in Business / Medical Administration", "6~12个月", 0, 4000, "部分州补贴")],
      qual=[("Certificate III in Health Administration (HLT37315)", "TAFE/RTO", "非强制但加分", 0)],
      listings=[("Seek", 2000, 3500, "全国"), ("Indeed", 1500, 2800, "全国")],
      sal=[("入门", 50000, 58000, "时薪约$26~$30"), ("有经验", 58000, 68000, "熟悉诊所软件"), ("资深", 68000, 75000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("很短", 1), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细心、有同理心的人", "想进入医疗行政路径者"],
      unfit=["以技术移民为目标者", "不适应医疗环境压力者"],
      faqs=[("salary", "澳洲医疗前台工资多少？", "约AUD $5万~$7.5万，熟悉Medicare和诊所软件有加成。"),
            ("migration", "医疗前台能技术移民吗？", "不能，属于非技术移民职业。")]),
 dict(code="512111", en="Office Manager", zh="办公室经理", cat="Business, Finance & Legal",
      mig=0, short=0, wf=120000, growth=["Operations Coordination", "HR & Payroll Admin", "Office Tech/SaaS"],
      sum_zh="办公室经理统筹日常行政、采购、设施、人事与财务协调，是中小企业的运营枢纽，多由资深行政晋升，非技术移民职业。",
      sum_en="Office managers coordinate admin, procurement, facilities, HR and finance support; an operations hub role, not a skilled migration occupation.",
      fc="中小企业持续需要全能型行政管理者，具备HR/财务/系统经验者薪资更高。", tr="可向运营经理、HR或Practice Manager发展。",
      edu=[("Diploma of Business / Leadership（常见）", "1~2年", 5000, 18000, "或经验晋升")],
      qual=[("Diploma of Leadership and Management (BSB50420)", "TAFE/RTO", "非强制", 0)],
      listings=[("Seek", 2500, 4500, "全国"), ("Indeed", 1800, 3200, "全国")],
      sal=[("初级", 65000, 78000, "中小企业"), ("中级（3-8年）", 78000, 95000, "—"), ("资深", 95000, 110000, "多职能")],
      visa=[],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["统筹能力强、细致的人", "资深行政想晋升管理者"],
      unfit=["以技术移民为目标者", "不愿承担多线协调压力者"],
      faqs=[("salary", "澳洲办公室经理工资多少？", "约AUD $6.5万~$11万，职能越全薪资越高。"),
            ("migration", "办公室经理能技术移民吗？", "不能，非技术移民职业。")]),
 # ---- 教育 ----
 dict(code="241213", en="Primary School Teacher", zh="小学教师", cat="Education & Community",
      mig=1, short=1, wf=180000, growth=["STEM Education", "Special Needs Support", "Regional/Remote Teaching", "EdTech"],
      sum_zh="小学教师负责K-6阶段的教学、班级管理与学生发展，是澳洲长期短缺、在 Core Skills 职业清单上的技术移民职业，需AITSL评估与注册。",
      sum_en="Primary teachers deliver K-6 education and class management; a shortage occupation on the Core Skills list with AITSL assessment and registration.",
      fc="全澳教师短缺，偏远与STEM方向尤其紧缺，州担保与雇主担保机会多。", tr="需完成4年高等教育（含教师教育资格）+ 各州教师注册；可向学科带头、副校长发展。",
      edu=[("Bachelor of Education (Primary)", "4年", 24000, 40000, "国际生约$100k~$150k总费"), ("Master of Teaching (Primary)", "2年", 30000, 50000, "已有学位者路径")],
      qual=[("AITSL Skills Assessment", "AITSL", "技术移民必备", 1), ("各州教师注册 (Teacher Registration)", "州教育主管部门", "合法执教强制", 1)],
      listings=[("Seek", 2500, 4500, "全国，含偏远"), ("各州教育局", 3000, 6000, "公立系统")],
      sal=[("毕业起薪", 75000, 85000, "Graduate teacher"), ("中级（4-8年）", 90000, 105000, "Proficient"), ("资深/Lead", 110000, 125000, "Highly Accomplished/Lead")],
      visa=VISA([("482", "Skills in Demand", "雇主担保，需AITSL评估"), ("190", "Skilled Nominated", "州提名，多州紧缺"), ("491", "Skilled Work Regional", "偏远地区加分"), ("186", "ENS", "永居通道")]),
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("较长", 4), "certification_difficulty": ("中高", 4),
           "job_demand": ("极高", 5), "competition": ("较低", 2), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), "pr_friendliness": ("高", 4), "pr_difficulty": ("中等", 3)},
      fit=["喜欢与孩子相处、有耐心的人", "想走教育类技术移民者", "愿意去偏远地区任教者"],
      unfit=["不适应课堂管理压力者", "不愿完成教师注册流程者"],
      faqs=[("salary", "澳洲小学教师工资多少？", "毕业起薪约AUD $7.5万~$8.5万，资深Lead教师可达$12.5万。"),
            ("migration", "小学教师能技术移民吗？", "可以。Primary School Teacher（241213）在Core Skills清单上，需AITSL评估和州教师注册，可走190/491/186等。"),
            ("difficulty", "小学教师难学吗？", "需4年本科或2年硕士的教师教育，难度中等，但注册和实习要求较严。")]),
 # ---- 餐饮/清洁 ----
 dict(code="811211", en="Commercial Cleaner", zh="商业清洁", cat="Creative, Media & Personal Services",
      mig=0, short=0, wf=160000, growth=["Specialised/Industrial Cleaning", "Hygiene & Sanitation", "Facility Services"],
      sum_zh="商业清洁在办公楼、商场、医院等场所进行清洁与卫生维护，受Cleaning Services Award保护，门槛低、夜班多，非技术移民职业。",
      sum_en="Commercial cleaners maintain hygiene in offices, malls and hospitals under the Cleaning Services Award; low-barrier, often night work, not a skilled migration occupation.",
      fc="需求稳定，专业化（医院/工业清洁）和设施服务方向附加值更高。", tr="可向清洁主管、设施服务承包发展。",
      edu=[("无强制学历（在岗培训）", "即时", 0, 0, "雇主培训"), ("Certificate III in Cleaning Operations（可选）", "数月", 0, 2500, "利于专业方向")],
      qual=[("White Card（部分工地需要）", "RTO", "工地清洁需要", 0)],
      listings=[("Seek", 3000, 6000, "全国，多casual"), ("Indeed", 2500, 5000, "全国")],
      sal=[("入门（casual）", 48000, 58000, "时薪约$24~$30含补贴"), ("全职", 55000, 65000, "Cleaning Award"), ("主管/专业清洁", 65000, 78000, "—")],
      visa=[],
      rat={"learning_difficulty": ("很低", 1), "learning_duration": ("很短", 1), "certification_difficulty": ("很低", 1),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("较低", 2), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["能吃苦、接受夜班者", "想灵活排班或快速上岗者"],
      unfit=["以技术移民为目标者", "不适应体力劳动者"],
      faqs=[("salary", "澳洲商业清洁工资多少？", "casual时薪约$24~$30，全职年薪约$5.5万~$6.5万，专业/主管$7万+。"),
            ("migration", "商业清洁能技术移民吗？", "不能，非技术移民职业。")]),
 dict(code="851311", en="Kitchenhand", zh="厨房帮工", cat="Hospitality, Retail & Tourism",
      mig=0, short=0, wf=120000, growth=["Food Prep", "Commercial Kitchen Ops", "Pathway to Cook/Chef"],
      sum_zh="厨房帮工协助备菜、清洗和厨房杂务，是餐饮业入门岗位，常作为转厨师的起点，受Hospitality Award保护，非技术移民职业。",
      sum_en="Kitchenhands assist with prep, washing and kitchen duties; an entry hospitality role and common stepping stone to cook/chef, not a skilled migration occupation.",
      fc="餐饮业用工需求大但流动性高；可作为转厨师的过渡。", tr="可向厨师、厨房主管发展（厨师为STSOL移民职业）。",
      edu=[("无强制学历（在岗培训）", "即时", 0, 0, "雇主培训")],
      qual=[("Food Safety / Food Handling（建议）", "在线/RTO", "部分场所要求", 0)],
      listings=[("Seek", 3000, 6000, "全国，多casual"), ("Indeed", 2500, 5000, "全国")],
      sal=[("入门（casual）", 48000, 56000, "时薪约$25~$30含补贴"), ("全职", 54000, 62000, "Hospitality Award")],
      visa=[],
      rat={"learning_difficulty": ("很低", 1), "learning_duration": ("很短", 1), "certification_difficulty": ("很低", 1),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("较低", 2), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["想入行餐饮、之后转厨师者", "能接受快节奏与轮班者"],
      unfit=["以技术移民为直接目标者", "不适应厨房高温与体力者"],
      faqs=[("salary", "澳洲厨房帮工工资多少？", "casual时薪约$25~$30，全职约$5.4万~$6.2万。"),
            ("migration", "厨房帮工能技术移民吗？", "不能。但可作为转厨师（Cook，STSOL移民职业）的起点。")]),
 dict(code="351411", en="Cook", zh="普通厨师", cat="Hospitality, Retail & Tourism",
      mig=1, short=1, wf=110000, growth=["Commercial Cookery", "Regional Hospitality", "Pathway to Chef"],
      sum_zh="厨师在餐厅、酒店、咖啡馆备餐烹饪，澳洲长期短缺，是STSOL上的技术移民职业（需TRA技能评估），偏远地区机会更多。",
      sum_en="Cooks prepare and cook food in restaurants and hotels; a shortage occupation on the STSOL with TRA assessment and strong regional demand.",
      fc="餐饮复苏与偏远地区用工短缺支撑需求，持证厨师移民路径清晰。", tr="需Certificate III/IV in Commercial Cookery + TRA评估；可向Chef、厨师长发展。",
      edu=[("Certificate III in Commercial Cookery (SIT30821)", "1~2年", 4000, 18000, "学徒制常见"), ("Certificate IV in Kitchen Management", "0.5~1年", 4000, 12000, "晋升/移民加分")],
      qual=[("Certificate III/IV in Commercial Cookery", "TAFE/RTO", "移民与执业基础", 1), ("TRA Skills Assessment", "Trades Recognition Australia", "技术移民必备", 1)],
      listings=[("Seek", 4000, 7000, "全国，含偏远"), ("Indeed", 3000, 5000, "全国")],
      sal=[("初级", 55000, 65000, "Cert III 起"), ("中级（3-6年）", 65000, 78000, "—"), ("资深/厨师长", 78000, 95000, "Chef de Partie+")],
      visa=VISA([("482", "Skills in Demand", "雇主担保，需TRA评估"), ("190", "Skilled Nominated", "州提名"), ("491", "Skilled Work Regional", "偏远地区加分，机会多"), ("186", "ENS", "永居通道")]),
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("很低", 1), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["热爱烹饪、能扛高强度厨房者", "愿去偏远地区积累移民分者"],
      unfit=["不适应长时间站立与高温者", "追求高起薪者"],
      faqs=[("salary", "澳洲厨师工资多少？", "初级约AUD $5.5万~$6.5万，资深/厨师长$7.8万~$9.5万。"),
            ("migration", "厨师能技术移民吗？", "可以。Cook（351411）在STSOL上，需Cert III/IV + TRA评估，偏远地区491机会较多。")]),
 dict(code="351111", en="Baker", zh="面包师糕点师", cat="Hospitality, Retail & Tourism",
      mig=1, short=1, wf=30000, growth=["Artisan Bakery", "Wholesale Baking", "Patisserie"],
      sum_zh="面包师糕点师制作面包、糕点和烘焙食品，澳洲长期短缺，是STSOL上的技术移民职业（需TRA评估），常需早班。",
      sum_en="Bakers and pastrycooks make breads and pastries; a shortage occupation on the STSOL with TRA assessment, often early starts.",
      fc="手工烘焙与连锁需求稳定，技工短缺支撑移民通道。", tr="需Certificate III in Baking/Patisserie + TRA评估；可向主面包师、店主发展。",
      edu=[("Certificate III in Baking (FBP30521)", "1~3年", 4000, 16000, "学徒制"), ("Certificate III in Patisserie", "1~2年", 4000, 14000, "糕点方向")],
      qual=[("Certificate III in Baking / Patisserie", "TAFE/RTO", "执业与移民基础", 1), ("TRA Skills Assessment", "Trades Recognition Australia", "技术移民必备", 1)],
      listings=[("Seek", 1200, 2200, "全国"), ("Indeed", 900, 1600, "全国")],
      sal=[("初级", 52000, 60000, "Cert III 起"), ("中级", 60000, 72000, "—"), ("资深/主面包师", 72000, 85000, "—")],
      visa=VISA([("482", "Skills in Demand", "雇主担保，需TRA评估"), ("190", "Skilled Nominated", "州提名"), ("491", "Skilled Work Regional", "偏远地区加分"), ("186", "ENS", "永居通道")]),
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("很低", 1), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["喜欢烘焙、能接受早班者", "想走技工移民路径者"],
      unfit=["不适应早起与重复工序者", "追求高薪者"],
      faqs=[("salary", "澳洲面包师工资多少？", "初级约AUD $5.2万~$6万，资深主面包师$7.2万~$8.5万。"),
            ("migration", "面包师能技术移民吗？", "可以。Baker（351111）在STSOL上，需Cert III + TRA评估。")]),
 # ---- 商业/金融/法律（管理类多为移民） ----
 dict(code="224711", en="Management Consultant", zh="管理顾问", cat="Business, Finance & Legal",
      mig=1, short=1, wf=70000, growth=["Strategy Consulting", "Digital Transformation", "Operations/Change Mgmt", "Data & Analytics Advisory"],
      sum_zh="管理顾问为企业提供战略、运营、组织和数字化转型咨询，是高薪专业职业，且在技术移民清单上（需VETASSESS评估）。",
      sum_en="Management consultants advise on strategy, operations and digital transformation; a well-paid profession on the skilled list via VETASSESS.",
      fc="数字化转型与降本增效需求推动咨询市场增长，资深顾问薪资很高。", tr="需相关学位+分析与沟通能力；路径向资深顾问、合伙人发展。",
      edu=[("Bachelor of Business/Commerce/Engineering", "3年", 25000, 45000, "—"), ("MBA / Master（加分）", "1~2年", 40000, 90000, "晋升加速")],
      qual=[("相关本科及以上", "认可大学", "入行基础", 0), ("VETASSESS Skills Assessment", "VETASSESS", "技术移民评估", 0)],
      listings=[("Seek", 1500, 2800, "全国"), ("LinkedIn", 1800, 3200, "偏咨询公司")],
      sal=[("初级（0-3年）", 80000, 105000, "Analyst/Consultant"), ("中级（3-8年）", 110000, 150000, "Senior/Manager"), ("资深/合伙人", 160000, 250000, "Principal/Partner")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中高", 4), "work_intensity": ("高", 5), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("高", 4), "pr_difficulty": ("中等", 3)},
      fit=["分析与沟通俱强、抗压者", "想走高薪专业+移民路径者"],
      unfit=["不愿高强度出差加班者", "不喜欢频繁变化项目者"],
      faqs=[("salary", "澳洲管理顾问工资多少？", "初级约AUD $8万~$10.5万，资深/合伙人可达$16万~$25万+。"),
            ("migration", "管理顾问能技术移民吗？", "可以。Management Consultant（224711）在技术移民清单上，需VETASSESS评估。")]),
 dict(code="132311", en="Human Resource Manager", zh="人力资源经理", cat="Business, Finance & Legal",
      mig=1, short=0, wf=60000, growth=["HR Analytics", "Talent Acquisition", "Employee Experience", "IR/ER"],
      sum_zh="人力资源经理负责招聘、薪酬、绩效、员工关系与组织发展，是高薪管理职业，在STSOL上（需VETASSESS评估）。",
      sum_en="HR managers oversee recruitment, remuneration, performance and employee relations; a well-paid management role on the STSOL via VETASSESS.",
      fc="组织对人才与文化投入增加，HR数据化与员工体验方向需求上升。", tr="需HR或商科背景+经验；路径向HR总监、首席人事官发展。",
      edu=[("Bachelor of Business (HR) / Commerce", "3年", 25000, 45000, "—"), ("AHRI 认证（加分）", "数月", 2000, 6000, "行业认可")],
      qual=[("相关本科及以上", "认可大学", "入行基础", 0), ("AHRI Certification（可选）", "AHRI", "行业认可", 0), ("VETASSESS Skills Assessment", "VETASSESS", "移民评估", 0)],
      listings=[("Seek", 1200, 2200, "全国"), ("LinkedIn", 1500, 2600, "—")],
      sal=[("初级HR经理", 95000, 120000, "—"), ("中级", 120000, 150000, "—"), ("资深/HR总监", 150000, 200000, "Director")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中高", 4), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["擅长沟通与组织管理者", "想走高薪管理+州担保移民者"],
      unfit=["不愿处理员工冲突与合规者", "排斥行政与数据工作者"],
      faqs=[("salary", "澳洲HR经理工资多少？", "约AUD $9.5万~$15万，HR总监可达$20万+。"),
            ("migration", "HR经理能技术移民吗？", "可以但有限。HR Manager（132311）在STSOL上，多走州提名或雇主担保，需VETASSESS评估。")]),
 dict(code="134211", en="Health and Welfare Services Manager", zh="医疗福利服务经理", cat="Healthcare & Care",
      mig=1, short=1, wf=40000, growth=["Aged Care Management", "Community Health", "NDIS/Disability Services", "Health Operations"],
      sum_zh="医疗福利服务经理管理医院科室、养老、社区健康和残障服务机构的运营、合规与团队，澳洲老龄化推动需求，在技术移民清单上。",
      sum_en="Health and welfare services managers run health, aged care and community service operations; demand driven by ageing, on the skilled list.",
      fc="老龄化、NDIS和社区健康扩张推动管理岗需求，合规与运营能力关键。", tr="需健康/管理背景+行业经验；路径向机构总监发展。",
      edu=[("Bachelor of Health/Nursing/Business", "3年", 25000, 45000, "—"), ("Master of Health Administration（加分）", "1.5~2年", 30000, 55000, "晋升")],
      qual=[("相关本科及以上", "认可大学", "入行基础", 0), ("VETASSESS Skills Assessment", "VETASSESS", "移民评估", 0)],
      listings=[("Seek", 1500, 2600, "全国，含偏远"), ("Indeed", 1000, 1900, "—")],
      sal=[("初级", 95000, 120000, "科室/中心"), ("中级", 120000, 150000, "—"), ("资深/总监", 150000, 200000, "多机构")],
      visa=VISA([("482", "Skills in Demand", "雇主担保"), ("190", "Skilled Nominated", "州提名，多州紧缺"), ("491", "Skilled Work Regional", "偏远加分"), ("186", "ENS", "永居")]),
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("较长", 4), "certification_difficulty": ("较低", 2),
           "job_demand": ("极高", 5), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), "pr_friendliness": ("高", 4), "pr_difficulty": ("中等", 3)},
      fit=["有医疗/护理背景想转管理者", "关注养老与社区服务者"],
      unfit=["不愿承担合规与人事压力者", "排斥医疗环境者"],
      faqs=[("salary", "澳洲医疗福利服务经理工资多少？", "约AUD $9.5万~$15万，机构总监可达$20万。"),
            ("migration", "医疗福利服务经理能技术移民吗？", "可以。Health and Welfare Services Manager（134211）在技术移民清单上，需VETASSESS评估，养老/社区方向紧缺。")]),
 dict(code="134214", en="Practice Manager", zh="诊所经理", cat="Healthcare & Care",
      mig=0, short=0, wf=30000, growth=["Medical Practice Ops", "Billing/Medicare", "Multi-site Management"],
      sum_zh="诊所经理负责全科/专科诊所的运营、财务、人事、Medicare结算与合规，多由资深医疗行政晋升，非技术移民职业。",
      sum_en="Practice managers run medical/dental clinic operations, finance, HR and Medicare billing; typically promoted from senior admin, not a skilled migration occupation.",
      fc="医疗诊所扩张支撑稳定需求，多店与专科诊所经理薪资更高。", tr="可向多店运营、医疗集团管理发展。",
      edu=[("Diploma of Practice Management / Business", "1~2年", 5000, 18000, "或经验晋升")],
      qual=[("Diploma of Practice Management（可选）", "RTO", "非强制", 0), ("AAPM 会员（加分）", "AAPM", "行业认可", 0)],
      listings=[("Seek", 1000, 1900, "全国"), ("Indeed", 700, 1400, "—")],
      sal=[("初级", 75000, 95000, "单店"), ("中级", 95000, 120000, "—"), ("资深/多店", 120000, 160000, "专科/多店")],
      visa=[],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["医疗行政经验想晋升者", "擅长运营与财务协调者"],
      unfit=["以技术移民为目标者", "不愿处理合规与人事者"],
      faqs=[("salary", "澳洲诊所经理工资多少？", "约AUD $7.5万~$16万，多店/专科更高。"),
            ("migration", "诊所经理能技术移民吗？", "不能，属于非技术移民职业。")]),
 # ---- 医疗辅助（非移民） ----
 dict(code="423211", en="Dental Assistant", zh="牙科助理", cat="Healthcare & Care",
      mig=0, short=0, wf=25000, growth=["Chairside Assisting", "Dental Radiography", "Practice Coordination"],
      sum_zh="牙科助理在牙科诊所协助医生进行椅旁操作、器械消毒、患者管理和预约，门槛低、可在岗培训，非技术移民职业。",
      sum_en="Dental assistants support dentists chairside with instruments, sterilisation and patient care; accessible with on-the-job training, not a skilled migration occupation.",
      fc="牙科服务需求稳定，持Cert III和放射资质者更抢手。", tr="可向资深牙助、诊所协调或Practice Manager发展。",
      edu=[("Certificate III/IV in Dental Assisting (HLT35021)", "1~2年", 0, 8000, "部分州补贴/在岗")],
      qual=[("Certificate III in Dental Assisting", "TAFE/RTO", "非强制但常要求", 0), ("Radiography 资质（加分）", "认可机构", "X光操作", 0)],
      listings=[("Seek", 1200, 2200, "全国"), ("Indeed", 900, 1600, "—")],
      sal=[("入门", 50000, 58000, "时薪约$26~$30"), ("有经验", 58000, 68000, "—"), ("资深/带放射资质", 68000, 78000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("较低", 2), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细心、有同理心想进牙科者", "想低门槛进入医疗辅助者"],
      unfit=["以技术移民为目标者", "不适应椅旁近距离操作者"],
      faqs=[("salary", "澳洲牙科助理工资多少？", "约AUD $5万~$7.8万，带放射资质更高。"),
            ("migration", "牙科助理能技术移民吗？", "不能，属于非技术移民职业。")]),
 dict(code="311299", en="Medical Technician", zh="医疗技术员", cat="Healthcare & Care",
      mig=0, short=0, wf=20000, growth=["Pathology/Lab Support", "Medical Equipment", "Cardiac/Respiratory Tech"],
      sum_zh="医疗技术员在实验室、医院和诊断中心协助样本处理、设备操作与检测支持（如病理、心肺技术），具体岗位需对应资质，一般非独立技术移民职业。",
      sum_en="Medical technicians support labs, diagnostics and equipment in pathology and hospitals; specific roles need relevant qualifications, generally not a standalone skilled migration occupation.",
      fc="诊断与检验需求随医疗扩张增长，专业方向（病理/心肺/影像）薪资更高。", tr="可考取专业资质向Medical Laboratory/Cardiac Technician等深化。",
      edu=[("Diploma/Bachelor in Laboratory/Medical Science", "1~3年", 8000, 35000, "视方向而定"), ("专业技术认证", "数月~1年", 1000, 8000, "对应岗位")],
      qual=[("相关 Diploma/Bachelor", "TAFE/大学", "视岗位要求", 0)],
      listings=[("Seek", 800, 1600, "全国"), ("Indeed", 600, 1200, "—")],
      sal=[("初级", 60000, 72000, "实验室/诊断"), ("中级", 72000, 88000, "专业方向"), ("资深", 88000, 105000, "—")],
      visa=[],
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("较低", 2), "pr_difficulty": ("中高", 4)},
      fit=["细致、对实验/设备操作有兴趣者", "想进入医疗技术方向者"],
      unfit=["期望直接独立技术移民者（需看具体资质）", "不适应重复精细操作者"],
      faqs=[("salary", "澳洲医疗技术员工资多少？", "约AUD $6万~$10.5万，专业方向（病理/心肺）更高。"),
            ("migration", "医疗技术员能技术移民吗？", "一般不作为独立技术移民职业，需看具体专业方向与资质是否对应清单职业（如医学实验科学家）。")]),
 dict(code="272199", en="Counsellor", zh="心理咨询师", cat="Healthcare & Care",
      mig=1, short=1, wf=40000, growth=["Mental Health", "Family/Relationship", "Drug & Alcohol", "Telehealth Counselling"],
      sum_zh="心理咨询师为个人、家庭提供情绪、心理健康、成瘾等咨询支持，澳洲心理健康需求上升，部分州可技术移民（需相关学位与评估）。",
      sum_en="Counsellors provide emotional, mental health and addiction support to individuals and families; rising demand, available on some state skilled lists.",
      fc="心理健康投入持续增加，远程咨询与专科方向需求快速上升。", tr="需相关本科/硕士+注册（如ACA/PACFA）；可向临床、专科方向发展。",
      edu=[("Bachelor of Counselling/Psychology", "3年", 25000, 42000, "—"), ("Master of Counselling", "1.5~2年", 28000, 50000, "专业方向")],
      qual=[("ACA / PACFA 注册", "行业协会", "执业与移民加分", 0), ("相关本科及以上", "认可大学", "入行基础", 0)],
      listings=[("Seek", 1500, 2600, "全国"), ("Indeed", 1000, 1900, "—")],
      sal=[("初级", 70000, 85000, "—"), ("中级", 85000, 105000, "—"), ("资深/专科", 105000, 125000, "私人执业更高")],
      visa=VISA([("190", "Skilled Nominated", "部分州提名"), ("491", "Skilled Work Regional", "偏远加分"), ("482", "Skills in Demand", "雇主担保"), ("186", "ENS", "永居")]),
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["有同理心、愿助人者", "关注心理健康领域并愿读相关学位者"],
      unfit=["不愿处理情绪压力者", "期望快速高薪者"],
      faqs=[("salary", "澳洲心理咨询师工资多少？", "约AUD $7万~$12.5万，私人执业与专科更高。"),
            ("migration", "心理咨询师能技术移民吗？", "可以但视州而定。Counsellor（272199）在部分州提名清单上，需相关学位与协会注册。")]),
 dict(code="224412", en="Policy Analyst", zh="政策分析师", cat="Business, Finance & Legal",
      mig=1, short=0, wf=25000, growth=["Public Policy", "Economic/Social Research", "Data-driven Policy", "Govt & NGO"],
      sum_zh="政策分析师在政府、智库和机构研究政策、评估影响并提出建议，需较强分析与写作能力，在技术移民清单上（需VETASSESS评估）。",
      sum_en="Policy analysts research and evaluate policy in government, think tanks and organisations; on the skilled list via VETASSESS.",
      fc="政府与机构对循证决策投入增加，数据驱动政策分析需求上升。", tr="需社科/经济/公共政策背景；路径向高级政策、研究主管发展。",
      edu=[("Bachelor in Economics/Political Science/Public Policy", "3年", 25000, 42000, "—"), ("Master of Public Policy（加分）", "1~2年", 30000, 55000, "—")],
      qual=[("相关本科及以上", "认可大学", "入行基础", 0), ("VETASSESS Skills Assessment", "VETASSESS", "移民评估", 0)],
      listings=[("Seek", 1000, 1900, "全国，偏政府/智库"), ("APS Jobs", 800, 1600, "联邦/州政府")],
      sal=[("初级", 80000, 95000, "—"), ("中级", 95000, 115000, "—"), ("资深/高级政策", 115000, 140000, "—")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中高", 4), "work_intensity": ("中等", 3), "income_level": ("中高", 3),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["分析与写作能力强者", "对公共政策/研究有热情者"],
      unfit=["不喜欢研究与报告写作者", "需要本地工作经验门槛较高者需注意"],
      faqs=[("salary", "澳洲政策分析师工资多少？", "约AUD $8万~$14万，高级政策岗更高。"),
            ("migration", "政策分析师能技术移民吗？", "可以。Policy Analyst（224412）在技术移民清单上，需VETASSESS评估。")]),
 # ---- 工程/生产管理（移民） ----
 dict(code="133211", en="Engineering Manager", zh="工程经理", cat="Engineering & Infrastructure",
      mig=1, short=1, wf=35000, growth=["Infrastructure Projects", "Renewables/Energy", "Manufacturing 4.0", "Project Delivery"],
      sum_zh="工程经理统筹工程项目的技术、团队、预算和交付，是高薪管理职业，在MLTSSL上（需EA或相关评估），基建与能源方向需求强。",
      sum_en="Engineering managers lead technical teams, budgets and delivery of engineering projects; a high-paid role on the MLTSSL via Engineers Australia.",
      fc="基建、可再生能源和制造升级推动工程管理需求，经验丰富者薪资很高。", tr="需工程背景+管理经验；路径向项目总监、运营总监发展。",
      edu=[("Bachelor of Engineering", "4年", 28000, 48000, "—"), ("MBA / Master（加分）", "1~2年", 40000, 80000, "管理晋升")],
      qual=[("Engineers Australia 评估 / CPEng", "Engineers Australia", "移民与执业加分", 0), ("相关工程本科", "认可大学", "入行基础", 0)],
      listings=[("Seek", 1500, 2800, "全国"), ("LinkedIn", 1800, 3200, "—")],
      sal=[("初级工程经理", 130000, 160000, "—"), ("中级", 160000, 200000, "—"), ("资深/总监", 200000, 260000, "大型项目")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("高", 5), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("很低", 1), "pr_friendliness": ("高", 4), "pr_difficulty": ("中等", 3)},
      fit=["工程背景想走管理高薪+移民者", "擅长项目与团队管理者"],
      unfit=["不愿承担交付与预算压力者", "排斥跨部门协调者"],
      faqs=[("salary", "澳洲工程经理工资多少？", "约AUD $13万~$26万，大型项目总监更高。"),
            ("migration", "工程经理能技术移民吗？", "可以。Engineering Manager（133211）在MLTSSL上，需Engineers Australia评估，189/190/186均可。")]),
 dict(code="133512", en="Production Manager (Manufacturing)", zh="生产经理", cat="Engineering & Infrastructure",
      mig=1, short=0, wf=40000, growth=["Lean Manufacturing", "Automation/Industry 4.0", "Supply Chain Integration", "Food/Pharma Production"],
      sum_zh="生产经理负责制造工厂的生产计划、质量、安全与团队，是技术移民职业（需VETASSESS评估），制造与食品/医药领域需求稳定。",
      sum_en="Production managers run manufacturing planning, quality, safety and teams; a skilled migration occupation via VETASSESS.",
      fc="制造自动化与本地供应链回流推动对精益与运营管理者的需求。", tr="需工程/制造背景+经验；路径向运营经理、厂长发展。",
      edu=[("Bachelor of Engineering/Manufacturing/Business", "3~4年", 25000, 45000, "—"), ("Lean/Six Sigma 认证（加分）", "数月", 1500, 6000, "—")],
      qual=[("相关本科及以上", "认可大学", "入行基础", 0), ("VETASSESS Skills Assessment", "VETASSESS", "移民评估", 0)],
      listings=[("Seek", 1200, 2200, "全国"), ("Indeed", 900, 1600, "—")],
      sal=[("初级", 95000, 120000, "—"), ("中级", 120000, 150000, "—"), ("资深/厂长", 150000, 190000, "大型工厂")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["制造/工程背景想做管理者", "擅长精益与流程优化者"],
      unfit=["不适应工厂现场与轮班者", "排斥安全合规工作者"],
      faqs=[("salary", "澳洲生产经理工资多少？", "约AUD $9.5万~$19万，大型工厂厂长更高。"),
            ("migration", "生产经理能技术移民吗？", "可以。Production Manager（133512）在技术移民清单上，需VETASSESS评估。")]),
 # ---- 运输（非移民） ----
 dict(code="731211", en="Bus Driver", zh="巴士司机", cat="Transport, Logistics & Mining",
      mig=0, short=1, wf=60000, growth=["Public Transport", "School Bus", "Coach/Charter", "EV Bus Fleets"],
      sum_zh="巴士司机驾驶公交、校车或长途客车，需重型驾照（HR/HC）和乘客认证，澳洲多地司机短缺，但属非技术移民职业。",
      sum_en="Bus drivers operate public, school or coach services with a heavy vehicle licence and passenger accreditation; in shortage but not a skilled migration occupation.",
      fc="公共交通与司机短缺支撑稳定需求，电动巴士车队带来新岗位。", tr="可向调度、车队管理或长途客运发展。",
      edu=[("HR/HC 重型驾照 + 乘客运输认证", "数周~数月", 1000, 5000, "考照与认证")],
      qual=[("Heavy Rigid (HR) Licence", "州交通部门", "驾驶巴士必备", 1), ("Driver Authorisation / Passenger Accreditation", "州主管部门", "载客必备", 1)],
      listings=[("Seek", 1500, 3000, "全国，多地短缺"), ("Indeed", 1200, 2200, "—")],
      sal=[("入门", 60000, 70000, "时薪约$30~$36"), ("有经验", 70000, 82000, "含轮班补贴"), ("长途/资深", 82000, 92000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("较低", 2), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["喜欢驾驶、责任心强者", "接受早晚轮班者"],
      unfit=["以技术移民为目标者", "不适应久坐与客流压力者"],
      faqs=[("salary", "澳洲巴士司机工资多少？", "约AUD $6万~$9.2万，含轮班补贴。"),
            ("migration", "巴士司机能技术移民吗？", "不能，属于非技术移民职业（尽管多地短缺）。")]),
 dict(code="621511", en="Retail Supervisor", zh="零售主管", cat="Hospitality, Retail & Tourism",
      mig=0, short=0, wf=90000, growth=["Team Leadership", "Visual Merchandising", "Inventory Control"],
      sum_zh="零售主管带领销售团队、负责排班、库存和日常运营，是销售员到店长之间的关键岗位，非技术移民职业。",
      sum_en="Retail supervisors lead sales teams, rostering, stock and daily operations; the step between sales assistant and store manager, not a skilled migration occupation.",
      fc="零售运营对一线带队者需求稳定，是晋升店长的必经岗位。", tr="可向店长、区域经理发展。",
      edu=[("无强制学历（经验晋升）", "—", 0, 0, "由资深销售晋升"), ("Certificate IV in Retail Management（可选）", "0.5~1年", 2000, 6000, "利于晋升")],
      qual=[("Certificate IV in Retail Management（可选）", "TAFE/RTO", "非强制", 0)],
      listings=[("Seek", 3000, 5500, "全国"), ("Indeed", 2200, 4000, "—")],
      sal=[("入门主管", 55000, 65000, "—"), ("有经验", 65000, 78000, "—"), ("资深/大店", 78000, 88000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("很低", 1),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中高", 4), "income_level": ("较低", 2),
           "future_prospect": ("中等", 3), "ai_risk": ("中等", 3), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["有零售经验想带团队者", "想走店长路径者"],
      unfit=["以技术移民为目标者", "不愿处理排班与周末班者"],
      faqs=[("salary", "澳洲零售主管工资多少？", "约AUD $5.5万~$8.8万。"),
            ("migration", "零售主管能技术移民吗？", "不能，属于非技术移民职业。")]),
 # ---- 金融文职（非移民） ----
 dict(code="551211", en="Bookkeeper", zh="记账员", cat="Business, Finance & Legal",
      mig=0, short=0, wf=90000, growth=["Cloud Accounting (Xero/MYOB)", "BAS Agent", "Payroll", "Small Business Advisory"],
      sum_zh="记账员负责日常账务、对账、发票、工资和BAS申报，广泛服务中小企业，云会计软件（Xero/MYOB）是核心技能，非技术移民职业。",
      sum_en="Bookkeepers handle day-to-day accounts, reconciliation, payroll and BAS for small businesses; cloud accounting is core, not a skilled migration occupation.",
      fc="中小企业持续需要记账服务，云会计与BAS Agent方向附加值更高。", tr="可考BAS Agent注册或向会计师方向深造。",
      edu=[("Certificate IV in Accounting and Bookkeeping (FNS40222)", "6~12个月", 2000, 6000, "BAS Agent前置")],
      qual=[("Certificate IV in Accounting and Bookkeeping", "TAFE/RTO", "BAS Agent前置", 0), ("Xero/MYOB 认证", "厂商", "实用加分", 0)],
      listings=[("Seek", 2500, 4500, "全国"), ("Indeed", 1800, 3200, "—")],
      sal=[("入门（0-2年）", 55000, 62000, "—"), ("中级（3-5年）", 62000, 78000, "—"), ("资深/BAS Agent", 78000, 95000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细心、对数字敏感者", "想低门槛进入财会者"],
      unfit=["以技术移民为目标者（建议读会计师）", "不喜欢重复账务者"],
      faqs=[("salary", "澳洲记账员工资多少？", "约AUD $5.5万~$9.5万，BAS Agent更高。"),
            ("migration", "记账员能技术移民吗？", "不能。记账员不在技术移民清单上；如要移民建议走会计师（Accountant）路径。")]),
 dict(code="551112", en="Payroll Clerk", zh="薪资文员", cat="Business, Finance & Legal",
      mig=0, short=0, wf=40000, growth=["Payroll Systems (MYOB/Xero/SAP)", "Award Interpretation", "STP Compliance"],
      sum_zh="薪资文员负责工资核算、考勤、单点报税（STP）、Award解读与合规，是企业薪酬运营的关键支持岗，非技术移民职业。",
      sum_en="Payroll clerks process wages, time records, STP reporting and award compliance; key payroll support, not a skilled migration occupation.",
      fc="薪酬合规复杂化使熟悉Award与系统的薪资专员需求稳定。", tr="可向薪酬主管、HR运营发展。",
      edu=[("Certificate IV in Accounting/Payroll（常见）", "6~12个月", 2000, 6000, "或在岗培训")],
      qual=[("Payroll 系统认证（MYOB/Xero/SAP）", "厂商", "实用加分", 0)],
      listings=[("Seek", 1500, 2800, "全国"), ("Indeed", 1000, 1900, "—")],
      sal=[("入门", 58000, 68000, "—"), ("有经验", 68000, 82000, "—"), ("资深/薪酬主管", 82000, 98000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细心、熟悉系统与合规者", "想进入薪酬/HR运营者"],
      unfit=["以技术移民为目标者", "不喜欢精确重复核算者"],
      faqs=[("salary", "澳洲薪资文员工资多少？", "约AUD $5.8万~$9.8万，薪酬主管更高。"),
            ("migration", "薪资文员能技术移民吗？", "不能，属于非技术移民职业。")]),
 dict(code="552111", en="Bank Worker", zh="银行职员", cat="Business, Finance & Legal",
      mig=0, short=0, wf=70000, growth=["Digital Banking", "Customer Service", "Lending Support", "Fraud/Compliance"],
      sum_zh="银行职员（柜员/客服）办理存取、转账、咨询和基础金融产品销售，受数字化银行冲击，门槛低，非技术移民职业。",
      sum_en="Bank workers (tellers/service) handle transactions, enquiries and basic product sales; pressured by digital banking, low-barrier, not a skilled migration occupation.",
      fc="网点收缩与数字化使柜员岗减少，但客服与贷款支持方向仍有机会。", tr="可向贷款、客户关系或合规方向发展。",
      edu=[("高中 / Certificate in Financial Services（可选）", "0~1年", 0, 5000, "在岗培训")],
      qual=[("Certificate III in Financial Services（可选）", "RTO", "非强制", 0)],
      listings=[("Seek", 1500, 3000, "全国"), ("Indeed", 1200, 2200, "—")],
      sal=[("入门柜员", 52000, 60000, "—"), ("客服/有经验", 60000, 72000, "—"), ("资深/贷款支持", 72000, 85000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("很低", 1),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("较低", 2),
           "future_prospect": ("较低", 2), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["沟通好、对金融有兴趣者", "想进入银行体系者"],
      unfit=["以技术移民为目标者", "排斥销售指标者"],
      faqs=[("salary", "澳洲银行职员工资多少？", "约AUD $5.2万~$8.5万。"),
            ("migration", "银行职员能技术移民吗？", "不能，属于非技术移民职业。")]),
 dict(code="552112", en="Credit and Loans Officer", zh="信贷专员", cat="Business, Finance & Legal",
      mig=0, short=0, wf=45000, growth=["Mortgage Lending", "Commercial Credit", "Credit Risk", "Broker Support"],
      sum_zh="信贷专员评估贷款申请、核查资料、计算额度并管理放款流程，服务银行与贷款机构，非技术移民职业。",
      sum_en="Credit and loans officers assess loan applications, verify documents and manage lending; in banks and lenders, not a skilled migration occupation.",
      fc="房贷与商业信贷需求稳定，信贷风险与合规方向更稳。", tr="可向信贷分析、抵押贷款经纪或风控发展。",
      edu=[("Certificate IV / Diploma in Finance and Mortgage Broking", "6~12个月", 1500, 6000, "—")],
      qual=[("Cert IV in Finance and Mortgage Broking (FNS40821)", "RTO", "贷款方向加分", 0)],
      listings=[("Seek", 1200, 2200, "全国"), ("Indeed", 800, 1500, "—")],
      sal=[("入门", 58000, 68000, "—"), ("有经验", 68000, 85000, "—"), ("资深/商业信贷", 85000, 105000, "—")],
      visa=[],
      rat={"learning_difficulty": ("较低", 2), "learning_duration": ("较短", 2), "certification_difficulty": ("较低", 2),
           "job_demand": ("中等", 3), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中等", 3),
           "future_prospect": ("中等", 3), "ai_risk": ("中高", 4), "pr_friendliness": ("很低", 1), "pr_difficulty": ("极高", 5)},
      fit=["细致、擅长核算与合规者", "想进入金融信贷者"],
      unfit=["以技术移民为目标者", "排斥流程与审核工作者"],
      faqs=[("salary", "澳洲信贷专员工资多少？", "约AUD $5.8万~$10.5万，商业信贷更高。"),
            ("migration", "信贷专员能技术移民吗？", "不能，属于非技术移民职业。")]),
 # ---- IT/通信（移民） ----
 dict(code="225212", en="ICT Business Development Manager", zh="ICT 销售", cat="IT & Digital",
      mig=1, short=0, wf=20000, growth=["SaaS/Cloud Sales", "Cybersecurity Sales", "Solution Selling", "Channel/Partnerships"],
      sum_zh="ICT销售（业务发展经理）负责软硬件、云和IT服务的客户开拓与方案销售，高薪且在技术移民清单上（需ACS或VETASSESS评估）。",
      sum_en="ICT sales / business development managers drive client acquisition and solution selling for software, cloud and IT services; high-paid, on the skilled list.",
      fc="云、SaaS与网络安全销售需求增长，提成使资深销售收入很高。", tr="需IT理解+销售能力；路径向销售总监、区域负责人发展。",
      edu=[("Bachelor of IT/Business（常见）", "3年", 25000, 45000, "或销售经验"), ("产品/云厂商认证（加分）", "数月", 1000, 5000, "—")],
      qual=[("相关本科（IT/商科）", "认可大学", "入行基础", 0), ("ACS / VETASSESS 评估", "ACS/VETASSESS", "移民评估", 0)],
      listings=[("Seek", 1000, 2000, "全国"), ("LinkedIn", 1500, 2800, "—")],
      sal=[("初级（含提成）", 80000, 110000, "Base+Commission"), ("中级", 110000, 150000, "—"), ("资深/总监", 150000, 220000, "高提成")],
      visa=VISA_MIG,
      rat={"learning_difficulty": ("中等", 3), "learning_duration": ("中等", 3), "certification_difficulty": ("较低", 2),
           "job_demand": ("旺盛", 4), "competition": ("中高", 4), "work_intensity": ("中高", 4), "income_level": ("高", 5),
           "future_prospect": ("良好", 4), "ai_risk": ("中等", 3), "pr_friendliness": ("中等", 3), "pr_difficulty": ("中高", 4)},
      fit=["懂IT又擅长销售沟通者", "想要高提成+移民路径者"],
      unfit=["排斥销售指标与客户开拓者", "不愿持续学习产品技术者"],
      faqs=[("salary", "澳洲ICT销售工资多少？", "含提成约AUD $8万~$22万，资深销售总监很高。"),
            ("migration", "ICT销售能技术移民吗？", "可以。ICT Business Development Manager（225212）在技术移民清单上，需ACS或VETASSESS评估。")]),
 dict(code="263311", en="Telecommunications Engineer", zh="通信工程师", cat="Engineering & Infrastructure",
      mig=1, short=1, wf=15000, growth=["5G/6G Networks", "Fibre/NBN", "IoT", "Network Security"],
      sum_zh="通信工程师设计、部署和优化通信网络（5G、光纤、IoT），是MLTSSL上的技术移民职业（需Engineers Australia评估），需求强。",
      sum_en="Telecommunications engineers design and optimise networks (5G, fibre, IoT); on the MLTSSL via Engineers Australia, strong demand.",
      fc="5G扩展、光纤升级和IoT推动通信工程需求，技能稀缺薪资较高。", tr="需通信/电子工程学位+EA评估；可向网络架构、技术经理发展。",
      edu=[("Bachelor of Engineering (Telecommunications/Electronics)", "4年", 28000, 48000, "—"), ("Master of Engineering（加分）", "1.5~2年", 30000, 55000, "—")],
      qual=[("Engineers Australia 评估 / CPEng", "Engineers Australia", "移民与执业", 0), ("相关工程本科", "认可大学", "入行基础", 0)],
      listings=[("Seek", 800, 1600, "全国"), ("LinkedIn", 900, 1700, "—")],
      sal=[("初级（0-3年）", 80000, 100000, "—"), ("中级（3-8年）", 100000, 130000, "—"), ("资深/架构", 130000, 160000, "—")],
      visa=VISA([("189", "Skilled Independent", "独立技术移民，MLTSSL"), ("190", "Skilled Nominated", "州提名"), ("491", "Skilled Work Regional", "偏远加分"), ("482", "Skills in Demand", "雇主担保")]),
      rat={"learning_difficulty": ("中高", 4), "learning_duration": ("较长", 4), "certification_difficulty": ("中等", 3),
           "job_demand": ("旺盛", 4), "competition": ("中等", 3), "work_intensity": ("中等", 3), "income_level": ("中高", 4),
           "future_prospect": ("良好", 4), "ai_risk": ("较低", 2), "pr_friendliness": ("高", 4), "pr_difficulty": ("中等", 3)},
      fit=["对网络与通信技术有兴趣者", "想走工程类技术移民者"],
      unfit=["不愿读工程学位者", "排斥现场与值班者"],
      faqs=[("salary", "澳洲通信工程师工资多少？", "约AUD $8万~$16万。"),
            ("migration", "通信工程师能技术移民吗？", "可以。Telecommunications Engineer（263311）在MLTSSL上，需Engineers Australia评估，可走189/190/491。")]),
]


def run():
    ok = 0
    for o in OCCS:
        OCC = {
            "occ_code": o["code"], "anzsco_code": o["code"], "anzsco_title": o["en"],
            "category": o["cat"], "workforce_size": o["wf"],
            "shortage_listed": o["short"], "is_migration": o["mig"],
            "growth_areas": json.dumps(o["growth"], ensure_ascii=False),
        }
        ZH = {"locale": "zh-CN", "name": o["zh"], "summary": o["sum_zh"],
              "forecast_note": o["fc"], "trend_summary": o["tr"]}
        EN = {"locale": "en", "name": o["en"], "summary": o["sum_en"],
              "forecast_note": o["fc"], "trend_summary": o["tr"]}
        sources = [{"source_name": s[0], "content": s[1], "url": s[2]} for s in (SRC_JSA, SRC_SEEK)]
        with get_cursor() as cur:
            seed_occupation_v2(cur, OCC, ZH, EN, EDU(o["edu"]), QUAL(o["qual"]),
                               LIST(o["listings"]), SAL(o["sal"]), o["visa"], R(o["rat"]),
                               o["fit"], o["unfit"], sources, FAQ(o["faqs"]))
        path = generate_md(o["code"])
        print(f"  [md] {o['zh']} -> {path.name}")
        ok += 1
    print(f"[OK] 批量入库完成 {ok}/{len(OCCS)}")


if __name__ == "__main__":
    run()
